// packages/vue/src/renderers/Text/index.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { WrapText, Code, Eye } from 'lucide-vue-next';
import { getLanguageFromFileName, fetchTextUtf8 } from '@pioneer/core';
import { useTranslator } from '../../composables/useTranslator';
import { useFetcher } from '../../composables/useRequest';
import { useShikiHighlight } from '../../composables/useShikiHighlight';
import { useDomSearch } from '../../composables/useDomSearch';
import RendererError from '../RendererError.vue';
import { ToolbarEventEmitter } from '../base.types';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';

const props = defineProps<{
  url: string;
  fileName: string;
}>();

const emitter = new ToolbarEventEmitter();

const { t } = useTranslator();
const fetcher = useFetcher();

// 内部状态
const wordWrap = ref(true);
const htmlPreview = ref(false);

const content = ref<string>('');
const loading = ref(true);
const error = ref<string | null>(null);
const rootRef = ref<HTMLDivElement | null>(null);
const search = useDomSearch(() => rootRef.value);

const language = computed(() => getLanguageFromFileName(props.fileName));
const codeForShiki = computed(() => (language.value !== 'text' ? content.value : ''));
const { lineHtmls } = useShikiHighlight(codeForShiki, language);

const isHtml = computed(() => language.value === 'html');

// 监听状态变化，通知工具栏更新
watch([wordWrap, htmlPreview, loading, isHtml], () => {
  emitter.notify();
});

const loadText = async () => {
  loading.value = true;
  error.value = null;
  try {
    const text = await fetchTextUtf8(props.url, { fetcher: fetcher.value });
    content.value = text;
  } catch (err) {
    console.error(err);
    error.value = t.value('text.load_failed');
  } finally {
    loading.value = false;
  }
};

watch(() => props.url, loadText, { immediate: true });

const lines = computed(() => content.value.split('\n'));

// 工具栏配置（对齐 React：WrapText 图标固定、Code/Eye 图标、翻译 key）
const getToolbarGroups = (): ToolbarGroup[] => {
  const groups: ToolbarGroup[] = [];

  groups.push({
    items: [
      {
        type: 'button',
        icon: WrapText,
        tooltip: wordWrap.value ? t.value('toolbar.wrap_off') : t.value('toolbar.wrap_on'),
        action: () => { wordWrap.value = !wordWrap.value; },
        active: wordWrap.value,
      },
    ],
  });

  if (isHtml.value) {
    groups.push({
      items: [
        {
          type: 'button',
          icon: htmlPreview.value ? Code : Eye,
          tooltip: htmlPreview.value ? t.value('toolbar.source') : t.value('toolbar.preview'),
          action: () => { htmlPreview.value = !htmlPreview.value; },
          active: htmlPreview.value,
        },
      ],
    });
  }

  return groups;
};

defineExpose<RendererHandle>({
  getToolbarGroups,
  onToolbarChange: (listener) => emitter.subscribe(listener),
  canSearch: () => search.canSearch,
  search: (query, options) => search.search(query, options),
  goToNextMatch: () => search.goToNextMatch(),
  goToPrevMatch: () => search.goToPrevMatch(),
  clearSearch: () => search.clearSearch(),
});
</script>

<template>
  <div ref="rootRef" v-if="loading" class="pio-flex pio-items-center pio-justify-center pio-w-full pio-h-full">
    <div
      class="pio-w-12 pio-h-12 pio-border-4 pio-border-line-strong pio-border-t-spinner-head pio-rounded-full pio-animate-spin"
    />
  </div>

  <RendererError v-else-if="error" :message="error" />

  <!-- HTML 预览模式 -->
  <div ref="rootRef" v-else-if="htmlPreview && language === 'html'" class="pio-w-full pio-h-full pio-bg-surface-toolbar">
    <iframe
      :srcdoc="content"
      sandbox="allow-same-origin"
      class="pio-w-full pio-h-full pio-border-0"
      :title="fileName"
    />
  </div>

  <!-- 纯文本或高亮未就绪：fallback -->
  <div ref="rootRef" v-else-if="language === 'text' || lineHtmls.length === 0" class="pio-w-full pio-h-full pio-overflow-auto" style="background: var(--pio-code-bg);">
    <pre
      class="pio-py-6 pio-px-4 pio-text-fg-primary pio-font-mono pio-text-sm"
      :class="wordWrap ? 'pio-whitespace-pre-wrap pio-break-words' : 'pio-whitespace-pre'"
    >{{ content }}</pre>
  </div>

  <!-- 双列布局：左 gutter（行号），右 code（shiki 高亮） -->
  <div ref="rootRef" v-else class="pio-w-full pio-h-full pio-overflow-auto" style="background: var(--pio-code-bg);">
    <div
      class="pio-code-block with-line-numbers pio-w-full"
      :class="{ 'no-wrap': !wordWrap }"
      :style="{ gridTemplateRows: `repeat(${lines.length}, auto) minmax(1.5rem, 1fr)` }"
    >
      <template v-for="(_, i) in lines" :key="i">
        <span class="pio-code-gutter">{{ i + 1 }}</span>
        <span class="pio-code-line" v-html="lineHtmls[i] ?? ''" />
      </template>
      <!-- 占位行：撑满剩余高度，让 gutter border 延伸到底部 -->
      <span class="pio-code-gutter-filler" />
      <span class="pio-code-line-filler" />
    </div>
  </div>
</template>

// packages/react/src/renderers/Text/index.tsx
import { useState, useEffect, Fragment, forwardRef, useCallback, useImperativeHandle, useRef } from 'react';
import { fetchTextUtf8, getLanguageFromFileName } from '@pioneer/core';
import { useTranslator } from '../../i18n/LocaleContext';
import { useFetcher } from '../../RequestContext';
import { useShikiHighlight } from '../../hooks/useShikiHighlight';
import { useDomSearch } from '../../hooks/useDomSearch';
import { RendererError } from '../RendererError';
import { WrapText, Code, Eye } from 'lucide-react';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';
import type { SearchOptions, SearchResult } from '@pioneer/core';

interface TextRendererProps {
  url: string;
  fileName: string;
}

export const TextRenderer = forwardRef<RendererHandle, TextRendererProps>(({
  url,
  fileName,
}, ref) => {
  const t = useTranslator();
  const fetcher = useFetcher();
  const rootRef = useRef<HTMLDivElement>(null);
  const search = useDomSearch(rootRef);

  // 内部状态管理
  const [content, setContent] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [wordWrap, setWordWrap] = useState(true);
  const [htmlPreview, setHtmlPreview] = useState(false);

  const language = getLanguageFromFileName(fileName);
  const { lineHtmls } = useShikiHighlight(
    language !== 'text' ? content : '',
    language,
  );

  useEffect(() => {
    const controller = new AbortController();
    const loadText = async () => {
      try {
        setLoading(true);
        setError(null);
        const text = await fetchTextUtf8(url, { fetcher, signal: controller.signal });
        setContent(text);
      } catch (err: any) {
        if (err.name === 'AbortError') return;
        setError(t('text.load_failed'));
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    loadText();
    return () => controller.abort();
  }, [url]);

  // 事件发射器：用于通知主组件工具栏状态变化
  const listenersRef = useRef<Set<() => void>>(new Set());
  const notifyToolbarChange = useCallback(() => {
    listenersRef.current.forEach(listener => listener());
  }, []);

  // 监听影响工具栏的状态变化
  useEffect(() => {
    notifyToolbarChange();
  }, [wordWrap, notifyToolbarChange]);

  useEffect(() => {
    notifyToolbarChange();
  }, [htmlPreview, notifyToolbarChange]);

  // 切换操作
  const toggleWordWrap = useCallback(() => {
    setWordWrap(prev => !prev);
  }, []);

  const toggleHtmlPreview = useCallback(() => {
    setHtmlPreview(prev => !prev);
  }, []);

  // 工具栏配置
  const getToolbarGroups = useCallback((): ToolbarGroup[] => {
    const groups: ToolbarGroup[] = [
      {
        items: [
          {
            type: 'button',
            icon: <WrapText className="pio-w-4 pio-h-4" />,
            tooltip: wordWrap ? t('toolbar.wrap_off') : t('toolbar.wrap_on'),
            action: toggleWordWrap,
            active: wordWrap,
          },
        ],
      },
    ];

    // HTML 文件显示预览按钮
    if (language === 'html') {
      groups.push({
        items: [
          {
            type: 'button',
            icon: htmlPreview
              ? <Code className="pio-w-4 pio-h-4" />
              : <Eye className="pio-w-4 pio-h-4" />,
            tooltip: htmlPreview ? t('toolbar.source') : t('toolbar.preview'),
            action: toggleHtmlPreview,
            active: htmlPreview,
          },
        ],
      });
    }

    return groups;
  }, [wordWrap, htmlPreview, language, t, toggleWordWrap, toggleHtmlPreview]);

  // 暴露接口给父组件
  useImperativeHandle(ref, () => ({
    getToolbarGroups,
    onToolbarChange: (listener: () => void) => {
      listenersRef.current.add(listener);
      return () => listenersRef.current.delete(listener);
    },
    canSearch: () => search.canSearch,
    search: (query: string, options?: SearchOptions): SearchResult => search.search(query, options),
    goToNextMatch: () => search.goToNextMatch(),
    goToPrevMatch: () => search.goToPrevMatch(),
    clearSearch: () => search.clearSearch(),
  }), [getToolbarGroups, search]);

  if (loading) {
    return (
      <div ref={rootRef} className="pio-flex pio-items-center pio-justify-center pio-w-full pio-h-full">
        <div className="pio-w-12 pio-h-12 pio-border-4 pio-border-line-strong pio-border-t-spinner-head pio-rounded-full pio-animate-spin" />
      </div>
    );
  }

  if (error) {
    return <div ref={rootRef} className="pio-w-full pio-h-full"><RendererError message={error} /></div>;
  }

  // HTML 预览模式
  if (htmlPreview && (language === 'html')) {
    return (
      <div ref={rootRef} className="pio-w-full pio-h-full pio-bg-surface-toolbar">
        <iframe
          srcDoc={content}
          sandbox="allow-same-origin"
          className="pio-w-full pio-h-full pio-border-0"
          title={fileName}
        />
      </div>
    );
  }

  // 纯文本或高亮未就绪：fallback 到普通 pre
  if (language === 'text' || lineHtmls.length === 0) {
    return (
      <div ref={rootRef} className="pio-w-full pio-h-full pio-overflow-auto pio-bg-code-bg">
        <pre
          className={`pio-py-6 pio-px-4 pio-text-fg-primary pio-font-mono pio-text-sm ${
            wordWrap ? 'pio-whitespace-pre-wrap pio-break-words' : 'pio-whitespace-pre'
          }`}
        >
          {content}
        </pre>
      </div>
    );
  }

  // 双列布局：左 gutter（行号），右 code（shiki 高亮）
  const lines = content.split('\n');
  return (
    <div ref={rootRef} className="pio-w-full pio-h-full pio-overflow-auto pio-bg-code-bg">
      <div
        className={`pio-code-block with-line-numbers ${wordWrap ? '' : 'no-wrap'} pio-w-full`}
        style={{ gridTemplateRows: `repeat(${lines.length}, auto) minmax(1.5rem, 1fr)` }}
      >
        {lines.map((_, i) => (
          <Fragment key={i}>
            <span className="pio-code-gutter">{i + 1}</span>
            <span
              className="pio-code-line"
              dangerouslySetInnerHTML={{ __html: lineHtmls[i] ?? '' }}
            />
          </Fragment>
        ))}
        {/* 占位行：撑满剩余高度，让 gutter border 延伸到底部 */}
        <span className="pio-code-gutter-filler" />
        <span className="pio-code-line-filler" />
      </div>
    </div>
  );
});
