// packages/react/src/renderers/Pdf/index.tsx
import { useState, useEffect, useRef, useCallback, useImperativeHandle, forwardRef } from 'react';
import { useTranslator } from '../../i18n/LocaleContext';
import { RendererError } from '../RendererError';
import { EncryptedPasswordModal } from '../../components/EncryptedPasswordModal';
import { X, ZoomIn, ZoomOut, ChevronLeft, ChevronRight, Menu, RefreshCw } from 'lucide-react';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';
// @ts-ignore - pdfjs-dist 类型路径
// Electron 环境使用 legacy 构建版本以避免 Web Streams API 兼容性问题
// 参考: https://github.com/mozilla/pdf.js/issues/16214
import * as pdfjsLib from 'pdfjs-dist/legacy/build/pdf.mjs';
import {
  configurePdfWorker,
  getPdfDocumentOptions,
  installUint8ArrayHexBase64Polyfill,
} from '@pioneer/core';

// 立即安装 Uint8Array hex/base64 polyfill。
// pdfjs 6.x 依赖 ES2025 的 Uint8Array.prototype.toHex/toBase64/fromBase64 等方法，
// 其 legacy 构建自带的 core-js polyfill 在 webpack/umi 二次打包时可能被 tree-shake，
// 导致 `TypeError: a.toHex is not a function`。此处主动安装（运行时调用，无法被消除）。
installUint8ArrayHexBase64Polyfill();

/**
 * 准备 PDF worker。
 *
 * - 浏览器环境：使用 CDN 上的 legacy worker（独立 worker 线程，自带 polyfill，性能好）。
 * - Electron 环境：worker 运行在缺少 Uint8Array hex/base64 polyfill 的独立作用域，
 *   会抛 `toHex is not a function`。此处将 worker 模块挂到 `globalThis.pdfjsWorker`，
 *   强制 pdfjs 在主线程执行 worker 逻辑（见 pdf.mjs PDFWorker#initialize），
 *   从而复用主线程已安装的 polyfill，并彻底绕开 CDN / worker 作用域问题。
 */
let pdfWorkerPrepared: Promise<void> | null = null;
function preparePdfWorker(): Promise<void> {
  if (pdfWorkerPrepared) return pdfWorkerPrepared;
  pdfWorkerPrepared = (async () => {
    const isElectron = typeof navigator !== 'undefined' && /electron/i.test(navigator.userAgent);
    if (isElectron) {
      const g = globalThis as any;
      if (typeof globalThis !== 'undefined' && !g.pdfjsWorker) {
        // @ts-ignore - pdfjs worker 无类型声明
        const workerModule = await import(/* webpackChunkName: "pdf.worker" */ /* @vite-ignore */ 'pdfjs-dist/legacy/build/pdf.worker.mjs');
        g.pdfjsWorker = workerModule;
      }
    }

    const configuredOptions = getPdfDocumentOptions();
    configurePdfWorker(pdfjsLib, {
      ...configuredOptions,
      workerSrc: pdfjsLib.GlobalWorkerOptions.workerSrc || undefined,
    });
  })();
  return pdfWorkerPrepared;
}

interface PdfOutlineItem {
  title: string;
  dest: any;
  items?: PdfOutlineItem[];
}

interface PdfPageProxy {
  getViewport(opts: { scale: number }): { width: number; height: number };
  render(opts: { canvasContext: CanvasRenderingContext2D; viewport: { width: number; height: number } }): {
    promise: Promise<void>;
    cancel(): void;
  };
}

interface PdfDocumentProxy {
  numPages: number;
  getPage(pageNumber: number): Promise<PdfPageProxy>;
  getOutline(): Promise<PdfOutlineItem[] | null>;
  destroy(): void;
}

interface PageState {
  element: HTMLDivElement;
  rendered: boolean;
  rendering: boolean;
  renderTask: { cancel(): void } | null;
}

export interface PdfRendererHandle extends RendererHandle {
  // 可选的公开方法
}

interface PdfRendererProps {
  url: string;
  /** 宿主传入的已知密码，跳过密码弹窗 */
  password?: string;
  /** 密码错误回调 */
  onPasswordError?: (error: string) => void;
}

export const PdfRenderer = forwardRef<PdfRendererHandle, PdfRendererProps>(({
  url,
  password: initialPassword,
  onPasswordError,
}, ref) => {
  const t = useTranslator();

  const MAX_PASSWORD_RETRIES = 3;

  // 内部状态管理
  const [zoom, setZoom] = useState(1);
  const [currentPage, setCurrentPage] = useState(1);
  const [numPages, setNumPages] = useState<number>(0);
  const [showOutline, setShowOutline] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [outline, setOutline] = useState<PdfOutlineItem[]>([]);
  const [activeOutlineItem, setActiveOutlineItem] = useState<string | null>(null);
  const outlinePageMapRef = useRef<Map<string, number>>(new Map());
  const containerRef = useRef<HTMLDivElement>(null);
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const pdfDocRef = useRef<PdfDocumentProxy | null>(null);
  const pageStatesRef = useRef<Map<number, PageState>>(new Map());
  const observerRef = useRef<IntersectionObserver | null>(null);
  const passwordRef = useRef<string | undefined>(initialPassword);

  // 密码弹窗状态
  const [needsPassword, setNeedsPassword] = useState(false);
  const [passwordError, setPasswordError] = useState('');
  const [passwordRetries, setPasswordRetries] = useState(MAX_PASSWORD_RETRIES);
  // 重试计数使用 ref 保存，避免进入 loadPdf 的依赖链导致 useEffect 循环重载
  const passwordRetriesRef = useRef(MAX_PASSWORD_RETRIES);
  const updatePasswordRetries = useCallback((n: number) => {
    passwordRetriesRef.current = n;
    setPasswordRetries(n);
  }, []);

  // 事件发射器：用于通知主组件工具栏状态变化
  const listenersRef = useRef<Set<() => void>>(new Set());
  const notifyToolbarChange = useCallback(() => {
    listenersRef.current.forEach(listener => listener());
  }, []);

  // 监听影响工具栏的状态变化
  useEffect(() => {
    notifyToolbarChange();
  }, [zoom, notifyToolbarChange]);

  useEffect(() => {
    notifyToolbarChange();
  }, [currentPage, notifyToolbarChange]);

  useEffect(() => {
    notifyToolbarChange();
  }, [numPages, notifyToolbarChange]);

  useEffect(() => {
    notifyToolbarChange();
  }, [outline.length, notifyToolbarChange]);

  // 渲染单个页面
  const renderPage = useCallback(async (pageNumber: number, scale: number) => {
    if (!pdfDocRef.current) return;
    const state = pageStatesRef.current.get(pageNumber);
    if (!state || state.rendering) return;

    state.rendering = true;

    try {
      const page = await pdfDocRef.current.getPage(pageNumber);
      const viewport = page.getViewport({ scale });

      const canvas = document.createElement('canvas');
      canvas.width = viewport.width;
      canvas.height = viewport.height;
      canvas.style.maxWidth = '100%';
      canvas.style.height = 'auto';
      canvas.style.borderRadius = '0';
      canvas.style.display = 'block';

      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      const renderTask = page.render({ canvasContext: ctx, viewport });
      state.renderTask = renderTask;
      await renderTask.promise;

      state.element.innerHTML = '';
      state.element.appendChild(canvas);

      state.rendered = true;
    } catch (err: any) {
      if (err?.name !== 'RenderingCancelledException') {
        console.error(`渲染页面 ${pageNumber} 失败:`, err);
      }
    } finally {
      state.rendering = false;
      state.renderTask = null;
    }
  }, []);

  // 清理页面 canvas
  const clearPageCanvas = useCallback((pageNumber: number) => {
    const state = pageStatesRef.current.get(pageNumber);
    if (!state) return;

    // 取消正在进行的渲染
    if (state.renderTask) {
      state.renderTask.cancel();
      state.renderTask = null;
    }

    // 清理 canvas
    const canvas = state.element.querySelector('canvas');
    if (canvas) {
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
      }
      canvas.remove();
    }

    state.element.innerHTML = '';
    state.rendered = false;
    state.rendering = false;
  }, []);

  // 初始化页面占位符
  // 构建大纲-页码映射
  const buildOutlinePageMap = async (items: PdfOutlineItem[], pdfDoc: PdfDocumentProxy, depth = 0) => {
    for (let i = 0; i < items.length; i++) {
      const item = items[i];
      const itemKey = `${item.title}-${i}-${depth}`;

      try {
        let pageNumber: number | null = null;
        const dest = item.dest;

        if (typeof dest === 'string') {
          const namedDest = await (pdfDoc as any).getDestination?.(dest);
          if (namedDest && namedDest[0] && typeof namedDest[0] === 'object') {
            pageNumber = await (pdfDoc as any).getPageIndex?.(namedDest[0]) + 1;
          }
        } else if (Array.isArray(dest) && dest[0] && typeof dest[0] === 'object') {
          pageNumber = await (pdfDoc as any).getPageIndex?.(dest[0]) + 1;
        }

        if (pageNumber !== null && pageNumber > 0) {
          outlinePageMapRef.current.set(itemKey, pageNumber);
        }

        if (item.items && item.items.length > 0) {
          await buildOutlinePageMap(item.items, pdfDoc, depth + 1);
        }
      } catch {
        // 静默失败，某些大纲项可能无法映射到页码
      }
    }
  };

  // 根据当前页码更新激活的大纲项
  const updateActiveOutlineByPage = useCallback((page: number) => {
    let closestItem: string | null = null;
    let closestDistance = Infinity;

    outlinePageMapRef.current.forEach((itemPage, itemKey) => {
      if (itemPage <= page) {
        const distance = page - itemPage;
        if (distance < closestDistance) {
          closestDistance = distance;
          closestItem = itemKey;
        }
      }
    });

    if (closestItem !== activeOutlineItem) {
      setActiveOutlineItem(closestItem);
    }
  }, [activeOutlineItem]);

  // 监听页码变化，更新大纲高亮
  useEffect(() => {
    if (currentPage > 0 && outlinePageMapRef.current.size > 0) {
      updateActiveOutlineByPage(currentPage);
    }
  }, [currentPage, updateActiveOutlineByPage]);

  const initPagePlaceholders = useCallback(() => {
    if (!pdfDocRef.current || !scrollContainerRef.current) return;

    const wrapper = scrollContainerRef.current.querySelector('.pdf-pages') as HTMLDivElement | null;
    if (!wrapper) return;

    wrapper.innerHTML = '';
    pageStatesRef.current.clear();

    for (let i = 1; i <= numPages; i++) {
      const pageDiv = document.createElement('div');
      pageDiv.className = 'pio-pdf-page-placeholder pio-relative pio-flex pio-justify-center';
      pageDiv.setAttribute('data-page-number', String(i));
      wrapper.appendChild(pageDiv);

      pageStatesRef.current.set(i, {
        element: pageDiv,
        rendered: false,
        rendering: false,
        renderTask: null,
      });

      // 观察页面元素
      if (observerRef.current) {
        observerRef.current.observe(pageDiv);
      }
    }
  }, [numPages]);

  // 加载 PDF 文档
  // resetRetries: 全新加载时重置重试计数；密码重试时传 false 保持递减
  const loadPdf = useCallback(async (opts?: { resetRetries?: boolean }) => {
    const resetRetries = opts?.resetRetries ?? true;
    setError(null);
    setIsLoading(true);
    setNumPages(0);
    setPasswordError('');
    if (resetRetries) {
      updatePasswordRetries(MAX_PASSWORD_RETRIES);
    }

    if (pdfDocRef.current) {
      try {
        pdfDocRef.current.destroy();
      } catch {
        // ignore
      }
      pdfDocRef.current = null;
    }

    try {
      // 准备 worker（浏览器用 CDN worker 线程；Electron 走主线程 worker 以复用 polyfill）
      // 若用户已通过 configurePdfjs 显式配置 workerSrc，则尊重其配置
      await preparePdfWorker();

      const loadOptions: any = {
        url,
        ...getPdfDocumentOptions(),
      };

      // 若有密码（初始传入或后续输入），附带密码参数
      if (passwordRef.current) {
        loadOptions.password = passwordRef.current;
      }

      const loadingTask = pdfjsLib.getDocument(loadOptions);
      pdfDocRef.current = await loadingTask.promise as unknown as PdfDocumentProxy;
      const total = pdfDocRef.current.numPages;

      setNumPages(total);
      setCurrentPage(1);

      // 提取大纲
      try {
        const outlineData = await pdfDocRef.current.getOutline();
        if (outlineData) {
          setOutline(outlineData);
          // 构建大纲-页码映射
          outlinePageMapRef.current.clear();
          await buildOutlinePageMap(outlineData, pdfDocRef.current);
        }
      } catch (err) {
        console.warn('PDF 大纲提取失败:', err);
      }

      setIsLoading(false);
    } catch (err: any) {
      // 检测是否为密码错误（pdfjs 多种异常形式）
      const isPasswordError =
        err?.name === 'PasswordException' ||
        err?.name === 'InvalidPasswordException' ||
        err?.code === 'PASSWORD_REQUIRED' ||
        err?.message?.includes('Password') ||
        err?.message?.includes('password') ||
        err?.message?.includes('_encrypted');

      if (isPasswordError) {
        // 密码缺失或错误
        if (passwordRef.current) {
          // 已提供密码但错误
          const remaining = passwordRetriesRef.current - 1;
          updatePasswordRetries(remaining);
          if (remaining <= 0) {
            setPasswordError(t('encrypted.max_attempts'));
            onPasswordError?.(t('encrypted.max_attempts'));
          } else {
            setPasswordError(t('encrypted.error'));
            setNeedsPassword(true);
          }
        } else {
          // 首次需要密码
          setNeedsPassword(true);
        }
        setIsLoading(false);
        return;
      }
      console.error('PDF 加载错误:', err);
      setError(t('pdf.load_failed'));
      setIsLoading(false);
    }
  }, [url, t, onPasswordError, updatePasswordRetries]);

  // 滚动处理
  const handleScroll = useCallback(() => {
    if (!scrollContainerRef.current || pageStatesRef.current.size === 0) return;

    const container = scrollContainerRef.current;
    const scrollTop = container.scrollTop;
    const containerHeight = container.clientHeight;
    const scrollCenter = scrollTop + containerHeight / 2;

    let currentVisiblePage = 1;
    let minDistance = Infinity;

    pageStatesRef.current.forEach((state, pageNumber) => {
      const rect = state.element.getBoundingClientRect();
      const containerRect = container.getBoundingClientRect();
      const pageCenter = rect.top - containerRect.top + rect.height / 2 + scrollTop;
      const distance = Math.abs(pageCenter - scrollCenter);

      if (distance < minDistance) {
        minDistance = distance;
        currentVisiblePage = pageNumber;
      }
    });

    if (currentVisiblePage !== currentPage) {
      setCurrentPage(currentVisiblePage);
    }
  }, [currentPage]);

  // 初始化 IntersectionObserver
  useEffect(() => {
    observerRef.current = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          const pageNumber = Number(entry.target.getAttribute('data-page-number'));
          if (!pageNumber) return;

          if (entry.isIntersecting) {
            // 页面进入视口，渲染
            renderPage(pageNumber, zoom);
          } else {
            // 页面离开视口，清理
            const state = pageStatesRef.current.get(pageNumber);
            if (state && state.rendered) {
              clearPageCanvas(pageNumber);
            }
          }
        });
      },
      {
        root: scrollContainerRef.current,
        rootMargin: '500px 0px',
        threshold: 0,
      }
    );

    return () => {
      if (observerRef.current) {
        observerRef.current.disconnect();
        observerRef.current = null;
      }
    };
  }, [zoom, renderPage, clearPageCanvas]);

  // 监听 URL 变化
  useEffect(() => {
    // 只有 URL 有效时才加载（避免空字符串或已 revoke 的 blob URL）
    if (url) {
      loadPdf();
    }
  }, [url, loadPdf]);

  // 监听 numPages 变化，初始化占位符
  useEffect(() => {
    if (numPages > 0) {
      // 等待 DOM 更新后初始化占位符
      setTimeout(() => {
        initPagePlaceholders();
      }, 0);
    }
  }, [numPages, initPagePlaceholders]);

  // 监听 zoom 变化（防抖）
  useEffect(() => {
    const timer = setTimeout(() => {
      // 清理所有已渲染页面
      pageStatesRef.current.forEach((state, pageNumber) => {
        if (state.rendered) {
          clearPageCanvas(pageNumber);
        }
      });

      // 触发重新渲染
      if (observerRef.current && scrollContainerRef.current) {
        pageStatesRef.current.forEach((state) => {
          observerRef.current?.unobserve(state.element);
          observerRef.current?.observe(state.element);
        });
      }
    }, 150);

    return () => clearTimeout(timer);
  }, [zoom, clearPageCanvas]);

  // 监听滚动事件
  useEffect(() => {
    const container = scrollContainerRef.current;
    if (!container) return;

    container.addEventListener('scroll', handleScroll);
    return () => container.removeEventListener('scroll', handleScroll);
  }, [handleScroll]);

  // 清理
  useEffect(() => {
    return () => {
      // 清理所有渲染任务
      pageStatesRef.current.forEach((state) => {
        if (state.renderTask) {
          state.renderTask.cancel();
        }
      });
      pageStatesRef.current.clear();

      if (pdfDocRef.current) {
        try {
          pdfDocRef.current.destroy();
        } catch {
          // ignore
        }
        pdfDocRef.current = null;
      }
    };
  }, []);

  // 处理大纲点击跳转
  const handleOutlineClick = useCallback(async (dest: any, itemKey: string, onClose?: () => void) => {
    if (!pdfDocRef.current || !scrollContainerRef.current) return;

    try {
      let pageNumber: number;

      if (typeof dest === 'string') {
        // 命名目标
        const namedDest = await (pdfDocRef.current as any).getDestination(dest);
        if (namedDest && namedDest[0]) {
          const pageRef = namedDest[0];
          pageNumber = await (pdfDocRef.current as any).getPageIndex(pageRef) + 1;
        } else {
          return;
        }
      } else if (Array.isArray(dest) && dest[0]) {
        // 直接页面引用
        const pageRef = dest[0];
        pageNumber = await (pdfDocRef.current as any).getPageIndex(pageRef) + 1;
      } else {
        return;
      }

      // 设置激活项
      setActiveOutlineItem(itemKey);

      // 滚动到目标页面
      const pages = scrollContainerRef.current.querySelectorAll('[data-page-number]');
      const targetPage = pages[pageNumber - 1];
      if (targetPage) {
        targetPage.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }

      // 跳转后自动关闭侧边栏
      if (onClose) {
        setTimeout(() => onClose(), 300);
      }
    } catch (err) {
      console.error('大纲跳转失败:', err);
    }
  }, []);

  // 渲染大纲项
  const renderOutlineItems = (items: PdfOutlineItem[], depth = 0, onClose?: () => void): React.ReactNode => {
    return (
      <ul style={{ marginLeft: depth > 0 ? 16 : 0 }}>
        {items.map((item, i) => {
          const itemKey = `${item.title}-${i}-${depth}`;
          const isActive = activeOutlineItem === itemKey;
          return (
            <li key={itemKey}>
              <button
                onClick={() => handleOutlineClick(item.dest, itemKey, onClose)}
                className={`pio-w-full pio-text-left pio-py-2 pio-px-3 pio-text-sm pio-rounded pio-transition-all pio-truncate ${
                  isActive
                    ? 'pio-bg-surface-2 pio-text-fg-primary pio-font-medium'
                    : 'pio-text-fg-secondary hover:pio-text-fg-primary hover:pio-bg-surface-2'
                }`}
                title={item.title}
              >
                {item.title}
              </button>
              {item.items && item.items.length > 0 && renderOutlineItems(item.items, depth + 1, onClose)}
            </li>
          );
        })}
      </ul>
    );
  };

  // 工具栏事件处理
  const handleZoomIn = useCallback(() => {
    setZoom(z => Math.min(z + 0.1, 3));
  }, []);

  const handleZoomOut = useCallback(() => {
    setZoom(z => Math.max(z - 0.1, 0.5));
  }, []);

  const handleReset = useCallback(() => {
    setZoom(1);
  }, []);

  const handlePrevPage = useCallback(() => {
    if (!scrollContainerRef.current) return;
    const container = scrollContainerRef.current;
    const pages = container.querySelectorAll('[data-page-number]');
    const targetPage = pages[Math.max(0, currentPage - 2)];
    if (targetPage) {
      targetPage.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }, [currentPage]);

  const handleNextPage = useCallback(() => {
    if (!scrollContainerRef.current) return;
    const container = scrollContainerRef.current;
    const pages = container.querySelectorAll('[data-page-number]');
    const targetPage = pages[Math.min(pages.length - 1, currentPage)];
    if (targetPage) {
      targetPage.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }, [currentPage, numPages]);

  const handleToggleOutline = useCallback(() => {
    setShowOutline(prev => !prev);
  }, []);

  // 密码提交处理
  const handlePasswordSubmit = useCallback((pwd: string) => {
    passwordRef.current = pwd;
    setNeedsPassword(false);
    setPasswordError('');
    // 重新加载 PDF（带密码）—— 不重置重试计数，保持递减
    loadPdf({ resetRetries: false });
  }, [loadPdf]);

  const handlePasswordClose = useCallback(() => {
    setNeedsPassword(false);
  }, []);

  // 工具栏配置
  const getToolbarGroups = useCallback((): ToolbarGroup[] => {
    const groups: ToolbarGroup[] = [];

    // 大纲按钮（如果有大纲）
    if (outline.length > 0) {
      groups.push({
        items: [
          { type: 'button', icon: <Menu className="pio-w-4 pio-h-4" />, tooltip: t('toolbar.outline'), action: handleToggleOutline, active: showOutline },
        ],
      });
    }

    // 翻页
    groups.push({
      items: [
        { type: 'button', icon: <ChevronLeft className="pio-w-4 pio-h-4" />, tooltip: t('toolbar.prev_page'), action: handlePrevPage, disabled: currentPage <= 1 },
        { type: 'text', content: `${currentPage} / ${numPages}`, minWidth: '4rem' },
        { type: 'button', icon: <ChevronRight className="pio-w-4 pio-h-4" />, tooltip: t('toolbar.next_page'), action: handleNextPage, disabled: currentPage >= numPages },
      ],
    });

    // 缩放
    groups.push({
      items: [
        { type: 'button', icon: <ZoomOut className="pio-w-4 pio-h-4" />, tooltip: t('toolbar.zoom_out'), action: handleZoomOut, disabled: zoom <= 0.5 },
        { type: 'text', content: `${Math.round(zoom * 100)}%`, minWidth: '3rem' },
        { type: 'button', icon: <ZoomIn className="pio-w-4 pio-h-4" />, tooltip: t('toolbar.zoom_in'), action: handleZoomIn, disabled: zoom >= 3 },
      ],
    });

    // 重置
    groups.push({
      items: [
        { type: 'button', icon: <RefreshCw className="pio-w-4 pio-h-4" />, tooltip: t('toolbar.reset'), action: handleReset },
      ],
    });

    return groups;
  }, [zoom, currentPage, numPages, showOutline, outline.length, t, handleZoomIn, handleZoomOut, handlePrevPage, handleNextPage, handleToggleOutline, handleReset]);

  // 暴露接口给父组件
  useImperativeHandle(ref, () => ({
    getToolbarGroups,
    onToolbarChange: (listener: () => void) => {
      listenersRef.current.add(listener);
      return () => listenersRef.current.delete(listener);
    },
  }), [getToolbarGroups]);

  return (
    <div ref={containerRef} className="pio-relative pio-w-full pio-h-full">
      {/* 大纲侧边栏 */}
      {outline.length > 0 && (
        <div
          className="pio-absolute pio-inset-0 pio-z-20 pio-flex pio-transition-opacity pio-duration-300"
          style={{
            opacity: showOutline ? 1 : 0,
            pointerEvents: showOutline ? 'auto' : 'none',
          }}
        >
          <div
            className="pio-w-72 pio-max-w-[80%] pio-h-full pio-bg-surface-overlay pio-backdrop-blur-xl pio-border-r pio-border-line-weak pio-flex pio-flex-col pio-shadow-2xl pio-transition-transform pio-duration-300"
            style={{ transform: showOutline ? 'translateX(0)' : 'translateX(-100%)' }}
          >
            <div className="pio-flex pio-items-center pio-justify-between pio-px-4 pio-py-3 pio-border-b pio-border-line-weak pio-flex-shrink-0">
              <span className="pio-text-fg-primary pio-font-medium pio-text-sm">{t('toolbar.outline')}</span>
              <button
                onClick={() => setShowOutline(false)}
                className="pio-text-fg-tertiary hover:pio-text-fg-primary pio-transition-colors"
              >
                <X className="pio-w-4 pio-h-4" />
              </button>
            </div>
            <div className="pio-flex-1 pio-overflow-y-auto pio-py-4 pio-px-1">
              {renderOutlineItems(outline, 0, () => setShowOutline(false))}
            </div>
          </div>
          <div
            className="pio-flex-1 pio-transition-opacity pio-duration-300"
            style={{ background: showOutline ? 'rgba(0,0,0,0.3)' : 'transparent' }}
            onClick={() => setShowOutline(false)}
          />
        </div>
      )}

      <div
        ref={scrollContainerRef}
        className="pio-pdf-container pio-w-full pio-h-full pio-overflow-auto pio-py-6 pio-px-4"
      >
        {error && (
          <RendererError message={error} />
        )}

        {!error && isLoading && (
          <div className="pio-flex pio-items-center pio-justify-center pio-min-h-screen">
            <div className="pio-w-12 pio-h-12 pio-border-4 pio-border-line-strong pio-border-t-spinner-head pio-rounded-full pio-animate-spin" />
          </div>
        )}

        {!error && (
          <div className="pio-flex pio-flex-col pio-items-center">
            <div className="pdf-pages pio-flex pio-flex-col pio-gap-4" />
          </div>
        )}
      </div>

      {/* 密码弹窗：当 PDF 需要密码时弹出 */}
      {needsPassword && (
        <EncryptedPasswordModal
          t={t}
          retriesLeft={passwordRetries}
          errorMessage={passwordError}
          onSubmit={handlePasswordSubmit}
          onClose={handlePasswordClose}
        />
      )}

      {/* 密码弹窗等待态：内容区显示提示 */}
      {needsPassword && !error && (
        <div className="pio-absolute pio-inset-0 pio-flex pio-items-center pio-justify-center pio-z-[5] pio-bg-black/20">
          <p className="pio-text-sm pio-text-fg-muted">{t('encrypted.waiting')}</p>
        </div>
      )}
    </div>
  );
});

// packages/vue/src/renderers/Pdf/index.vue
<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount, nextTick } from 'vue';
import {
  configurePdfWorker,
  getPdfDocumentOptions,
  installUint8ArrayHexBase64Polyfill,
} from '@pioneer/core';
// @ts-ignore - pdfjs-dist 类型路径
// Electron 环境使用 legacy 构建版本以避免 Web Streams API 兼容性问题
// 参考: https://github.com/mozilla/pdf.js/issues/16214
import * as pdfjsLib from 'pdfjs-dist/legacy/build/pdf.mjs';
import { useTranslator } from '../../composables/useTranslator';
import RendererError from '../RendererError.vue';
import EncryptedPasswordModal from '../../components/EncryptedPasswordModal.vue';
import { X, ZoomIn, ZoomOut, ChevronLeft, ChevronRight, Menu, RefreshCw } from 'lucide-vue-next';
import { ToolbarEventEmitter } from '../base.types';
import type { RendererHandle } from '../base.types';

// 立即安装 Uint8Array hex/base64 polyfill（pdfjs 6.x 必需，防止 webpack/umi tree-shake）
installUint8ArrayHexBase64Polyfill();

/**
 * 准备 PDF worker。
 * - 浏览器：使用 CDN 上的 legacy worker（独立 worker 线程，性能好）。
 * - Electron：worker 独立作用域缺 Uint8Array hex/base64 polyfill，会抛 `toHex is not a function`。
 *   将 worker 模块挂到 `globalThis.pdfjsWorker`，强制 pdfjs 主线程执行 worker 逻辑，
 *   复用主线程已装的 polyfill，并绕开 CDN / worker 作用域问题。
 */
let pdfWorkerPrepared: Promise<void> | null = null;
function preparePdfWorker(): Promise<void> {
  if (pdfWorkerPrepared) return pdfWorkerPrepared;
  pdfWorkerPrepared = (async () => {
    const isElectron = typeof navigator !== 'undefined' && /electron/i.test(navigator.userAgent);
    if (isElectron) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const g = globalThis as any;
      if (typeof globalThis !== 'undefined' && !g.pdfjsWorker) {
        // @ts-ignore - pdfjs worker 无类型声明
        const workerModule = await import(/* webpackChunkName: "pdf.worker" */ /* @vite-ignore */ 'pdfjs-dist/legacy/build/pdf.worker.mjs');
        g.pdfjsWorker = workerModule;
      }
    }

    const configuredOptions = getPdfDocumentOptions();
    configurePdfWorker(pdfjsLib, {
      ...configuredOptions,
      workerSrc: pdfjsLib.GlobalWorkerOptions.workerSrc || undefined,
    });
  })();
  return pdfWorkerPrepared;
}
import type { ToolbarGroup } from '../toolbar.types';

interface PdfOutlineItem {
  title: string;
  dest: any;
  items?: PdfOutlineItem[];
}

interface PdfPageProxy {
  getViewport(opts: { scale: number }): { width: number; height: number };
  render(opts: { canvasContext: CanvasRenderingContext2D; viewport: { width: number; height: number } }): {
    promise: Promise<void>;
    cancel(): void;
  };
}

interface PdfDocumentProxy {
  numPages: number;
  getPage(pageNumber: number): Promise<PdfPageProxy>;
  getOutline(): Promise<PdfOutlineItem[] | null>;
  destroy(): void;
}

interface PageState {
  element: HTMLDivElement;
  rendered: boolean;
  rendering: boolean;
  renderTask: any;
}

const props = defineProps<{
  url: string;
  password?: string;
}>();

const emitter = new ToolbarEventEmitter();

const { t } = useTranslator();

// 内部状态管理
const zoom = ref(1);
const currentPage = ref(1);
const showOutline = ref(false);
const numPages = ref(0);
const error = ref<string | null>(null);
const isLoading = ref(true);
const outline = ref<PdfOutlineItem[]>([]);
const activeOutlineItem = ref<string | null>(null);
const containerRef = ref<HTMLDivElement | null>(null);
const scrollContainerRef = ref<HTMLDivElement | null>(null);
const outlinePageMap = new Map<string, number>();
let pdfDoc: PdfDocumentProxy | null = null;
const pageStates = new Map<number, PageState>();
let observer: IntersectionObserver | null = null;

// 密码相关状态
const MAX_PASSWORD_RETRIES = 3;
const needsPassword = ref(false);
const passwordError = ref('');
const passwordRetries = ref(MAX_PASSWORD_RETRIES);
const currentPassword = ref<string | undefined>(undefined);

// 通知工具栏变化
watch([zoom, currentPage, numPages, showOutline, () => outline.value.length], () => {
  emitter.notify();
});

// 工具栏操作
const handleZoomIn = () => {
  zoom.value = Math.min(3, zoom.value + 0.1);
};
const handleZoomOut = () => {
  zoom.value = Math.max(0.5, zoom.value - 0.1);
};
const handleReset = () => {
  zoom.value = 1;
};
const handlePrevPage = () => {
  if (!scrollContainerRef.value) return;
  const pages = scrollContainerRef.value.querySelectorAll('[data-page-number]');
  const targetPage = pages[Math.max(0, currentPage.value - 2)];
  if (targetPage) {
    targetPage.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }
};
const handleNextPage = () => {
  if (!scrollContainerRef.value) return;
  const pages = scrollContainerRef.value.querySelectorAll('[data-page-number]');
  const targetPage = pages[Math.min(pages.length - 1, currentPage.value)];
  if (targetPage) {
    targetPage.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }
};
const handleToggleOutline = () => {
  showOutline.value = !showOutline.value;
};

// 工具栏配置
const getToolbarGroups = (): ToolbarGroup[] => {
  const groups: ToolbarGroup[] = [];

  if (numPages.value === 0) return groups;

  if (outline.value.length > 0) {
    groups.push({
      items: [
        {
          type: 'button',
          icon: Menu,
          tooltip: t.value('toolbar.outline'),
          action: handleToggleOutline,
          active: showOutline.value,
        },
      ],
    });
  }

  groups.push({
    items: [
      {
        type: 'button',
        icon: ChevronLeft,
        tooltip: t.value('toolbar.prev_page'),
        action: handlePrevPage,
        disabled: currentPage.value <= 1,
      },
      {
        type: 'text',
        content: `${currentPage.value} / ${numPages.value}`,
        minWidth: '4rem',
      },
      {
        type: 'button',
        icon: ChevronRight,
        tooltip: t.value('toolbar.next_page'),
        action: handleNextPage,
        disabled: currentPage.value >= numPages.value,
      },
    ],
  });

  groups.push({
    items: [
      {
        type: 'button',
        icon: ZoomOut,
        tooltip: t.value('toolbar.zoom_out'),
        action: handleZoomOut,
        disabled: zoom.value <= 0.5,
      },
      {
        type: 'text',
        content: `${Math.round(zoom.value * 100)}%`,
        minWidth: '3rem',
      },
      {
        type: 'button',
        icon: ZoomIn,
        tooltip: t.value('toolbar.zoom_in'),
        action: handleZoomIn,
        disabled: zoom.value >= 3,
      },
    ],
  });

  groups.push({
    items: [
      {
        type: 'button',
        icon: RefreshCw,
        tooltip: t.value('toolbar.reset'),
        action: handleReset,
      },
    ],
  });

  return groups;
};

defineExpose<RendererHandle>({
  getToolbarGroups,
  onToolbarChange: (listener) => emitter.subscribe(listener),
});

// 构建大纲-页码映射
const buildOutlinePageMap = async (items: PdfOutlineItem[], pdfDocument: PdfDocumentProxy, depth = 0) => {
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const itemKey = `${item.title}-${i}-${depth}`;

    try {
      let pageNumber: number | null = null;
      const dest = item.dest;

      if (typeof dest === 'string') {
        const namedDest = await (pdfDocument as any).getDestination?.(dest);
        if (namedDest && namedDest[0] && typeof namedDest[0] === 'object') {
          pageNumber = await (pdfDocument as any).getPageIndex?.(namedDest[0]) + 1;
        }
      } else if (Array.isArray(dest) && dest[0] && typeof dest[0] === 'object') {
        pageNumber = await (pdfDocument as any).getPageIndex?.(dest[0]) + 1;
      }

      if (pageNumber !== null && pageNumber > 0) {
        outlinePageMap.set(itemKey, pageNumber);
      }

      if (item.items && item.items.length > 0) {
        await buildOutlinePageMap(item.items, pdfDocument, depth + 1);
      }
    } catch (err) {
      // 静默失败
    }
  }
};

// 根据当前页码更新激活的大纲项
const updateActiveOutlineByPage = (page: number) => {
  let closestItem: string | null = null;
  let closestDistance = Infinity;

  outlinePageMap.forEach((itemPage, itemKey) => {
    if (itemPage <= page) {
      const distance = page - itemPage;
      if (distance < closestDistance) {
        closestDistance = distance;
        closestItem = itemKey;
      }
    }
  });

  if (closestItem !== activeOutlineItem.value) {
    activeOutlineItem.value = closestItem;
  }
};

// 处理大纲点击跳转
const handleOutlineClick = async (dest: any, itemKey: string) => {
  if (!pdfDoc || !scrollContainerRef.value) return;

  try {
    let pageNumber: number;

    if (typeof dest === 'string') {
      const namedDest = await (pdfDoc as any).getDestination?.(dest);
      if (namedDest && namedDest[0]) {
        pageNumber = await (pdfDoc as any).getPageIndex?.(namedDest[0]) + 1;
      } else {
        return;
      }
    } else if (Array.isArray(dest) && dest[0]) {
      pageNumber = await (pdfDoc as any).getPageIndex?.(dest[0]) + 1;
    } else {
      return;
    }

    // 设置激活项
    activeOutlineItem.value = itemKey;

    // 滚动到目标页面
    const pages = scrollContainerRef.value.querySelectorAll('[data-page-number]');
    const targetPage = pages[pageNumber - 1];
    if (targetPage) {
      targetPage.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }

    // 跳转后自动关闭侧边栏
    setTimeout(() => { showOutline.value = false; }, 300);
  } catch (err) {
    console.error('大纲跳转失败:', err);
  }
};

// 渲染大纲项（递归组件会更复杂，这里用简单的方式）
const renderOutlineItemsHtml = (items: PdfOutlineItem[], depth = 0): string => {
  return items.map((item, i) => {
    const itemKey = `${item.title}-${i}-${depth}`;
    const isActive = activeOutlineItem.value === itemKey;
    const activeClass = isActive
      ? 'pio-bg-surface-2 pio-text-fg-primary pio-font-medium'
      : 'pio-text-fg-secondary hover:pio-text-fg-primary hover:pio-bg-surface-2';

    let html = `<li style="margin-left: ${depth > 0 ? 16 : 0}px;">
      <button
        data-outline-key="${itemKey}"
        data-outline-dest="${JSON.stringify(item.dest).replace(/"/g, '&quot;')}"
        class="pio-w-full pio-text-left pio-py-2 pio-px-3 pio-text-sm pio-rounded pio-transition-all pio-truncate ${activeClass}"
        title="${item.title}"
      >
        ${item.title}
      </button>`;

    if (item.items && item.items.length > 0) {
      html += `<ul>${renderOutlineItemsHtml(item.items, depth + 1)}</ul>`;
    }

    html += '</li>';
    return html;
  }).join('');
};

const renderPage = async (pageNumber: number, scale: number) => {
  if (!pdfDoc) return;
  const state = pageStates.get(pageNumber);
  if (!state || state.rendering) return;

  state.rendering = true;

  try {
    const page = await pdfDoc.getPage(pageNumber);
    const viewport = page.getViewport({ scale });

    const canvas = document.createElement('canvas');
    canvas.width = viewport.width;
    canvas.height = viewport.height;
    canvas.style.maxWidth = '100%';
    canvas.style.height = 'auto';
    canvas.style.borderRadius = '0';
    canvas.style.display = 'block';

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const renderTask = page.render({ canvasContext: ctx, viewport });
    state.renderTask = renderTask;
    await renderTask.promise;

    state.element.innerHTML = '';
    state.element.appendChild(canvas);

    state.rendered = true;
  } catch (err: any) {
    if (err?.name !== 'RenderingCancelledException') {
      console.error(`渲染页面 ${pageNumber} 失败:`, err);
    }
  } finally {
    state.rendering = false;
    state.renderTask = null;
  }
};

const clearPageCanvas = (pageNumber: number) => {
  const state = pageStates.get(pageNumber);
  if (!state) return;

  if (state.renderTask) {
    state.renderTask.cancel();
    state.renderTask = null;
  }

  const canvas = state.element.querySelector('canvas');
  if (canvas) {
    const ctx = canvas.getContext('2d');
    if (ctx) {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
    }
  }

  state.element.innerHTML = '';
  state.rendered = false;
  state.rendering = false;
};

const initPagePlaceholders = () => {
  if (!pdfDoc || !scrollContainerRef.value) return;

  const wrapper = scrollContainerRef.value.querySelector('.pdf-pages') as HTMLDivElement | null;
  if (!wrapper) return;

  wrapper.innerHTML = '';
  pageStates.clear();

  for (let i = 1; i <= numPages.value; i++) {
    const pageDiv = document.createElement('div');
    pageDiv.className = 'pio-pdf-page-placeholder pio-relative pio-flex pio-justify-center';
    pageDiv.setAttribute('data-page-number', String(i));
    wrapper.appendChild(pageDiv);

    pageStates.set(i, {
      element: pageDiv,
      rendered: false,
      rendering: false,
      renderTask: null,
    });

    if (observer) {
      observer.observe(pageDiv);
    }
  }
};

const loadPdf = async (opts?: { resetRetries?: boolean }) => {
  const resetRetries = opts?.resetRetries ?? true;
  error.value = null;
  isLoading.value = true;
  numPages.value = 0;
  passwordError.value = '';
  if (resetRetries) {
    passwordRetries.value = MAX_PASSWORD_RETRIES;
  }

  if (pdfDoc) {
    try {
      pdfDoc.destroy();
    } catch {
      // ignore
    }
    pdfDoc = null;
  }

  try {
    // 准备 worker（浏览器用 CDN worker 线程；Electron 走主线程 worker 以复用 polyfill）
    // 若用户已显式配置 workerSrc，则尊重其配置
    await preparePdfWorker();

    const loadOptions: any = {
      url: props.url,
      ...getPdfDocumentOptions(),
    };

    // 若有密码（初始传入或后续输入），附带密码参数
    if (props.password || currentPassword.value) {
      loadOptions.password = props.password || currentPassword.value;
    }

    const loadingTask = pdfjsLib.getDocument(loadOptions);
    pdfDoc = await loadingTask.promise as unknown as PdfDocumentProxy;
    const total = pdfDoc.numPages;

    numPages.value = total;
    currentPage.value = 1;

    // 提取大纲
    try {
      const outlineData = await pdfDoc.getOutline();
      if (outlineData) {
        outline.value = outlineData;
        // 构建大纲-页码映射
        outlinePageMap.clear();
        await buildOutlinePageMap(outlineData, pdfDoc);
      }
    } catch (err) {
      console.warn('PDF 大纲提取失败:', err);
    }

    isLoading.value = false;
  } catch (err: any) {
    // 检测是否为密码错误（pdfjs 多种异常形式）
    const isPasswordError =
      err?.name === 'PasswordException' ||
      err?.name === 'InvalidPasswordException' ||
      err?.code === 'PASSWORD_REQUIRED' ||
      err?.message?.includes('Password') ||
      err?.message?.includes('password') ||
      err?.message?.includes('_encrypted');

    if (isPasswordError) {
      const hasPassword = !!props.password || !!currentPassword.value;
      if (hasPassword) {
        // 已提供密码但错误
        const remaining = passwordRetries.value - 1;
        passwordRetries.value = remaining;
        if (remaining <= 0) {
          passwordError.value = t.value('encrypted.max_attempts');
        } else {
          passwordError.value = t.value('encrypted.error');
          needsPassword.value = true;
        }
      } else {
        // 首次需要密码
        needsPassword.value = true;
      }
      isLoading.value = false;
      return;
    }
    console.error('PDF 加载错误:', err);
    error.value = t.value('pdf.load_failed');
    isLoading.value = false;
  }
};

const handleScroll = () => {
  if (!scrollContainerRef.value || pageStates.size === 0) return;

  const container = scrollContainerRef.value;
  const scrollTop = container.scrollTop;
  const containerHeight = container.clientHeight;
  const scrollCenter = scrollTop + containerHeight / 2;

  let currentVisiblePage = 1;
  let minDistance = Infinity;

  pageStates.forEach((state, pageNumber) => {
    const rect = state.element.getBoundingClientRect();
    const containerRect = container.getBoundingClientRect();
    const pageCenter = rect.top - containerRect.top + rect.height / 2 + scrollTop;

    const distance = Math.abs(scrollCenter - pageCenter);
    if (distance < minDistance) {
      minDistance = distance;
      currentVisiblePage = pageNumber;
    }
  });

  if (currentVisiblePage !== currentPage.value) {
    currentPage.value = currentVisiblePage;
  }
};

// 设置大纲点击事件代理
const setupOutlineEventDelegation = () => {
  nextTick(() => {
    const outlineContainer = containerRef.value?.querySelector('.outline-items');
    if (!outlineContainer) return;

    outlineContainer.addEventListener('click', (e: Event) => {
      const target = e.target as HTMLElement;
      const button = target.closest('[data-outline-key]');
      if (!button) return;

      const itemKey = button.getAttribute('data-outline-key');
      const destStr = button.getAttribute('data-outline-dest');
      if (!itemKey || !destStr) return;

      try {
        const dest = JSON.parse(destStr);
        handleOutlineClick(dest, itemKey);
      } catch (err) {
        console.error('解析大纲目标失败:', err);
      }
    });
  });
};

// 监听 URL 变化
watch(() => props.url, () => {
  if (props.url) {
    loadPdf();
  }
}, { immediate: true });

// 监听 password prop 变化，重新加载
watch(() => props.password, () => {
  if (props.password && needsPassword.value) {
    currentPassword.value = undefined;
    needsPassword.value = false;
    passwordError.value = '';
    loadPdf();
  }
});

// 密码提交
const handlePasswordSubmit = (pwd: string) => {
  currentPassword.value = pwd;
  needsPassword.value = false;
  passwordError.value = '';
  loadPdf({ resetRetries: false });
};

// 密码弹窗关闭
const handlePasswordClose = () => {
  needsPassword.value = false;
};

// 监听 numPages 变化，初始化占位符
watch(numPages, (val) => {
  if (val > 0) {
    nextTick(() => {
      initPagePlaceholders();
    });
  }
});

// 监听 zoom 变化
watch(() => zoom.value, () => {
  pageStates.forEach((state, pageNumber) => {
    if (state.rendered) {
      clearPageCanvas(pageNumber);
    }
  });

  setTimeout(() => {
    if (observer && scrollContainerRef.value) {
      pageStates.forEach((state) => {
        observer?.unobserve(state.element);
        observer?.observe(state.element);
      });
    }
  }, 150);
});

// 监听 currentPage 变化，更新大纲高亮
watch(() => currentPage.value, (page) => {
  if (page > 0 && outlinePageMap.size > 0) {
    updateActiveOutlineByPage(page);
  }
});

// 监听 activeOutlineItem 变化，更新大纲 UI
watch(activeOutlineItem, () => {
  nextTick(() => {
    const outlineContainer = containerRef.value?.querySelector('.outline-items');
    if (!outlineContainer) return;

    // 重新渲染大纲项
    if (outline.value.length > 0) {
      outlineContainer.innerHTML = `<ul>${renderOutlineItemsHtml(outline.value)}</ul>`;
      // 重新绑定事件
      setupOutlineEventDelegation();
    }
  });
});

// 监听 outline 变化，渲染大纲
watch(outline, () => {
  nextTick(() => {
    const outlineContainer = containerRef.value?.querySelector('.outline-items');
    if (!outlineContainer && outline.value.length > 0) {
      // 容器还没准备好，等待下一次
      setTimeout(() => {
        const container = containerRef.value?.querySelector('.outline-items');
        if (container) {
          container.innerHTML = `<ul>${renderOutlineItemsHtml(outline.value)}</ul>`;
          setupOutlineEventDelegation();
        }
      }, 100);
    } else if (outlineContainer && outline.value.length > 0) {
      outlineContainer.innerHTML = `<ul>${renderOutlineItemsHtml(outline.value)}</ul>`;
      setupOutlineEventDelegation();
    }
  });
}, { deep: true });

onMounted(() => {
  // 设置 IntersectionObserver
  observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        const pageNumber = Number(entry.target.getAttribute('data-page-number'));
        if (!pageNumber) return;

        if (entry.isIntersecting) {
          renderPage(pageNumber, zoom.value);
        } else {
          const state = pageStates.get(pageNumber);
          if (state && state.rendered) {
            clearPageCanvas(pageNumber);
          }
        }
      });
    },
    {
      root: scrollContainerRef.value,
      rootMargin: '500px 0px',
      threshold: 0,
    }
  );

  // 监听滚动
  const container = scrollContainerRef.value;
  if (container) {
    container.addEventListener('scroll', handleScroll);
  }
});

onBeforeUnmount(() => {
  // 清理
  if (observer) {
    observer.disconnect();
    observer = null;
  }

  const container = scrollContainerRef.value;
  if (container) {
    container.removeEventListener('scroll', handleScroll);
  }

  pageStates.forEach((state) => {
    if (state.renderTask) {
      state.renderTask.cancel();
    }
  });
  pageStates.clear();

  if (pdfDoc) {
    try {
      pdfDoc.destroy();
    } catch {
      // ignore
    }
    pdfDoc = null;
  }
});
</script>

<template>
  <div ref="containerRef" class="pio-relative pio-w-full pio-h-full">
    <!-- 大纲侧边栏 -->
    <div
      v-if="outline.length > 0"
      class="pio-absolute pio-inset-0 pio-z-20 pio-flex pio-transition-opacity pio-duration-300"
      :style="{
        opacity: showOutline ? 1 : 0,
        pointerEvents: showOutline ? 'auto' : 'none',
      }"
    >
      <div
        class="pio-w-72 pio-max-w-[80%] pio-h-full pio-bg-surface-overlay pio-backdrop-blur-xl pio-border-r pio-border-line-weak pio-flex pio-flex-col pio-shadow-2xl pio-transition-transform pio-duration-300"
        :style="{ transform: showOutline ? 'translateX(0)' : 'translateX(-100%)' }"
      >
        <div class="pio-flex pio-items-center pio-justify-between pio-px-4 pio-py-3 pio-border-b pio-border-line-weak pio-flex-shrink-0">
          <span class="pio-text-fg-primary pio-font-medium pio-text-sm">{{ t('toolbar.outline') }}</span>
          <button
            @click="showOutline = false"
            class="pio-text-fg-tertiary hover:pio-text-fg-primary pio-transition-colors"
          >
            <X class="pio-w-4 pio-h-4" />
          </button>
        </div>
        <div class="pio-flex-1 pio-overflow-y-auto pio-py-4 pio-px-1 outline-items" v-html="renderOutlineItemsHtml(outline)" />
      </div>
      <div
        class="pio-flex-1 pio-transition-opacity pio-duration-300"
        :style="{ background: showOutline ? 'rgba(0,0,0,0.3)' : 'transparent' }"
        @click="showOutline = false"
      />
    </div>

    <div
      ref="scrollContainerRef"
      class="pio-pdf-container pio-w-full pio-h-full pio-overflow-auto"
    >
      <RendererError v-if="error" :message="error" />

      <div v-if="!error && isLoading" class="pio-flex pio-items-center pio-justify-center pio-min-h-screen">
        <div
          class="pio-w-12 pio-h-12 pio-border-4 pio-border-line-strong pio-border-t-spinner-head pio-rounded-full pio-animate-spin"
        />
      </div>

      <div v-if="!error" class="pio-flex pio-flex-col pio-items-center">
        <div class="pdf-pages pio-flex pio-flex-col pio-gap-4" />
      </div>
    </div>

    <!-- 密码弹窗等待态 -->
    <div
      v-if="needsPassword && !error"
      class="pio-absolute pio-inset-0 pio-flex pio-items-center pio-justify-center pio-z-[5] pio-bg-black/20"
    >
      <p class="pio-text-sm pio-text-fg-muted">{{ t('encrypted.waiting') }}</p>
    </div>

    <!-- 密码弹窗 -->
    <EncryptedPasswordModal
      v-if="needsPassword"
      :retries-left="passwordRetries"
      :error-message="passwordError"
      @submit="handlePasswordSubmit"
      @close="handlePasswordClose"
    />
  </div>
</template>
