// packages/vue/src/PioneerEmbed.vue
<script setup lang="ts">
import { ref, watch, onBeforeUnmount, computed } from 'vue';
import type { CSSProperties } from 'vue';
import type { PreviewFile, PreviewFileInput, Locale, Messages, Theme, CustomRendererEventPayload, RequestHandler, RequestInitFactory, ShouldFetchAsBlob, WatermarkConfig } from '@pioneer/core';
import type { CustomRenderer } from './types';
import PioneerContent from './PioneerContent.vue';

interface Props {
  files: PreviewFileInput[];
  currentIndex?: number;
  customRenderers?: CustomRenderer[];
  /** 宽度,默认 100% 填充父容器 */
  width?: number | string;
  /** 高度,默认 100% 填充父容器 */
  height?: number | string;
  /** 语言 */
  locale?: Locale;
  /** 自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  /** 无头模式：隐藏工具栏和导航箭头 */
  headless?: boolean;
  /** 主题模式，默认 'dark' */
  theme?: Theme;
  /** 自定义 RequestInit（或工厂函数）：注入 Authorization 等鉴权头 */
  requestInit?: RequestInitFactory;
  /** 自定义请求处理器：完全接管库内 fetch */
  requestHandler?: RequestHandler;
  /** 返回 true 时，对应文件先 fetcher→blob URL 后喂给 image/video/audio/pdf 等 renderer */
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  /** 自定义下载回调；不传时库内默认通过 fetcher 拉 Blob 触发下载 */
  onDownload?: (file: PreviewFile) => void | Promise<void>;
  /** 关闭回调 */
  onClose?: () => void;
  /** 是否显示关闭按钮，默认根据 mode 决定（embed: false） */
  showClose?: boolean;
  /** 是否显示下载按钮，默认 true */
  showDownload?: boolean;
  /** 水印配置 */
  watermark?: WatermarkConfig;
  /** 加密文件密码 */
  password?: string;
}

const props = withDefaults(defineProps<Props>(), {
  currentIndex: 0,
  customRenderers: () => [],
  width: '100%',
  height: '100%',
  locale: undefined,
  messages: undefined,
  headless: false,
  theme: 'dark',
  requestInit: undefined,
  requestHandler: undefined,
  shouldFetchAsBlob: undefined,
  onDownload: undefined,
  onClose: undefined,
  showClose: undefined,
  showDownload: true,
});

const emit = defineEmits<{
  (e: 'navigate', index: number): void;
  (e: 'custom-event', payload: CustomRendererEventPayload): void;
  (e: 'close'): void;
}>();

const systemDark = ref(
  typeof window !== 'undefined'
    ? window.matchMedia('(prefers-color-scheme: dark)').matches
    : true,
);

let mediaQueryCleanup: (() => void) | null = null;

watch(
  () => props.theme,
  (theme) => {
    if (mediaQueryCleanup) {
      mediaQueryCleanup();
      mediaQueryCleanup = null;
    }
    if (theme === 'auto') {
      const mql = window.matchMedia('(prefers-color-scheme: dark)');
      const handler = (e: MediaQueryListEvent) => { systemDark.value = e.matches; };
      mql.addEventListener('change', handler);
      mediaQueryCleanup = () => mql.removeEventListener('change', handler);
    }
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  if (mediaQueryCleanup) mediaQueryCleanup();
});

const resolvedTheme = computed(() =>
  props.theme === 'auto' ? (systemDark.value ? 'dark' : 'light') : props.theme,
);

const wrapperStyle: CSSProperties = {
  width: typeof props.width === 'number' ? `${props.width}px` : props.width,
  height: typeof props.height === 'number' ? `${props.height}px` : props.height,
};
</script>

<template>
  <div class="pio-root" :style="wrapperStyle" :data-theme="resolvedTheme">
    <div class="pio-relative pio-w-full pio-h-full pio-overflow-hidden pio-bg-surface-overlay">
      <PioneerContent
        mode="embed"
        :files="files"
        :current-index="currentIndex"
        :custom-renderers="customRenderers"
        :locale="locale"
        :messages="messages"
        :headless="headless"
        :theme="theme"
        :request-init="requestInit"
        :request-handler="requestHandler"
        :should-fetch-as-blob="shouldFetchAsBlob"
        :on-download="onDownload"
        :on-close="onClose"
        :show-close="showClose"
        :show-download="showDownload"
        :watermark="watermark"
        :password="password"
        @navigate="(i) => emit('navigate', i)"
        @custom-event="(p) => emit('custom-event', p)"
        @close="() => emit('close')"
      />
    </div>
  </div>
</template>

// packages/react/src/PioneerEmbed.tsx
import { useEffect, useState } from 'react';
import { PreviewFileInput, CustomRenderer } from './types';
import { PioneerContent } from './PioneerContent';
import type { Locale, Messages, Theme, CustomRendererEventPayload, PreviewFile, RequestHandler, RequestInitFactory, ShouldFetchAsBlob, WatermarkConfig } from '@pioneer/core';

interface PioneerEmbedProps {
  files: PreviewFileInput[];
  currentIndex?: number;
  onNavigate?: (index: number) => void;
  customRenderers?: CustomRenderer[];
  /** 宽度,默认 100% 填充父容器 */
  width?: number | string;
  /** 高度,默认 100% 填充父容器 */
  height?: number | string;
  className?: string;
  style?: React.CSSProperties;
  /** 国际化语言，默认 'zh-CN' */
  locale?: Locale;
  /** 用户自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  /** 无头模式：隐藏工具栏和导航箭头 */
  headless?: boolean;
  /** 主题模式，默认 'dark' */
  theme?: Theme;
  /** 自定义渲染器派发的事件出口 */
  onCustomEvent?: (event: CustomRendererEventPayload) => void;
  /** 自定义 RequestInit（或工厂函数）：注入 Authorization 等鉴权头 */
  requestInit?: RequestInitFactory;
  /** 自定义请求处理器：完全接管库内 fetch */
  requestHandler?: RequestHandler;
  /** 返回 true 时，对应文件先 fetcher→blob URL 后喂给 image/video/audio/pdf 等 renderer */
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  /** 自定义下载回调；不传时库内默认通过 fetcher 拉 Blob 触发下载 */
  onDownload?: (file: PreviewFile) => void | Promise<void>;
  /** 关闭回调 */
  onClose?: () => void;
  /** 是否显示关闭按钮，默认根据 mode 决定（embed: false） */
  showClose?: boolean;
  /** 是否显示下载按钮，默认 true */
  showDownload?: boolean;
  /** 水印配置 */
  watermark?: WatermarkConfig;
  /** 加密文件密码 */
  password?: string;
}

export const PioneerEmbed: React.FC<PioneerEmbedProps> = ({
  files,
  currentIndex = 0,
  onNavigate,
  customRenderers = [],
  width = '100%',
  height = '100%',
  className,
  style,
  locale,
  messages,
  headless,
  theme = 'dark',
  onCustomEvent,
  requestInit,
  requestHandler,
  shouldFetchAsBlob,
  onDownload,
  onClose,
  showClose,
  showDownload,
  watermark,
  password,
}) => {
  const [systemDark, setSystemDark] = useState(() =>
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-color-scheme: dark)').matches
      : true,
  );

  useEffect(() => {
    if (theme !== 'auto') return;
    const mql = window.matchMedia('(prefers-color-scheme: dark)');
    const handler = (e: MediaQueryListEvent) => setSystemDark(e.matches);
    mql.addEventListener('change', handler);
    return () => mql.removeEventListener('change', handler);
  }, [theme]);

  const resolvedTheme = theme === 'auto' ? (systemDark ? 'dark' : 'light') : theme;

  return (
    <div
      className={`pio-root ${className ?? ''}`}
      style={{ width, height, ...style }}
      data-theme={resolvedTheme}
    >
      <div className="pio-relative pio-w-full pio-h-full pio-overflow-hidden pio-bg-surface-overlay">
        <PioneerContent
          mode="embed"
          files={files}
          currentIndex={currentIndex}
          onNavigate={onNavigate}
          customRenderers={customRenderers}
          locale={locale}
          messages={messages}
          headless={headless}
          theme={theme}
          onCustomEvent={onCustomEvent}
          requestInit={requestInit}
          requestHandler={requestHandler}
          shouldFetchAsBlob={shouldFetchAsBlob}
          onDownload={onDownload}
          onClose={onClose}
          showClose={showClose}
          showDownload={showDownload}
          watermark={watermark}
          password={password}
        />
      </div>
    </div>
  );
};
