// packages/vue/src/renderers/Epub/index.vue
<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount } from 'vue';
import ePub from '@likecoin/epub-ts';
import { X, ChevronLeft, ChevronRight, List, Maximize2, Minimize2 } from 'lucide-vue-next';
import { useTranslator } from '../../composables/useTranslator';
import { useFetcher } from '../../composables/useRequest';
import RendererError from '../RendererError.vue';
import { ToolbarEventEmitter } from '../base.types';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';

interface TocItem {
  label: string;
  href: string;
  subitems?: TocItem[];
}

interface RenditionLike {
  display: (target?: string) => Promise<unknown>;
  next: () => Promise<unknown>;
  prev: () => Promise<unknown>;
  on: (event: string, cb: (...args: unknown[]) => void) => void;
  resize: (width: number, height: number) => void;
  currentLocation: () => unknown;
  destroy?: () => void;
  themes: {
    register: (name: string, styles: Record<string, unknown>) => void;
    select: (name: string) => void;
  };
}

interface BookLike {
  ready: Promise<unknown>;
  loaded: { navigation: Promise<unknown> };
  locations: {
    generate: (chars: number) => Promise<string[]>;
    length: () => number;
    locationFromCfi: (cfi: string) => number;
  };
  renderTo: (el: HTMLElement, opts: Record<string, unknown>) => RenditionLike;
  destroy: () => void;
}

const A4_WIDTH = 794;

const props = defineProps<{ url: string }>();

const emitter = new ToolbarEventEmitter();

const { t } = useTranslator();
const fetcher = useFetcher();

// 内部状态
const currentChapter = ref(1);
const totalChapters = ref(1);

const viewerRef = ref<HTMLDivElement | null>(null);
const loading = ref(true);
const error = ref<string | null>(null);
const isFullWidth = ref(false);
const toc = ref<TocItem[]>([]);
const showToc = ref(false);
const activeTocHref = ref('');

// 监听状态变化，通知工具栏更新（对齐 React：增加 toc.length 监听）
watch([currentChapter, totalChapters, isFullWidth, showToc, () => toc.value.length], () => {
  emitter.notify();
});

let book: BookLike | null = null;
let rendition: RenditionLike | null = null;
let totalLocations = 0;
let lastCfi: string | null = null;

const cleanup = () => {
  try { rendition?.destroy?.(); } catch { /* ignore */ }
  try { book?.destroy(); } catch { /* ignore */ }
  rendition = null;
  book = null;
  totalLocations = 0;
  lastCfi = null;
};

const prevPage = () => { rendition?.prev(); };
const nextPage = () => { rendition?.next(); };
const toggleFullWidth = () => {
  isFullWidth.value = !isFullWidth.value;
  setTimeout(() => {
    if (viewerRef.value && rendition) {
      rendition.resize(viewerRef.value.offsetWidth, viewerRef.value.offsetHeight);
      if (lastCfi) {
        rendition.display(lastCfi);
      }
      reattachScrollListener();
    }
  }, 350);
};
const toggleToc = () => { showToc.value = !showToc.value; };
const handleTocClick = (href: string) => {
  activeTocHref.value = href;
  rendition?.display(href);
  showToc.value = false;
};

const isActive = (href: string) => {
  return href === activeTocHref.value;
};

// 工具栏配置（对齐 React：List 图标、disabled 代替条件、Minimize2/Maximize2 切换）
const getToolbarGroups = (): ToolbarGroup[] => [
  {
    items: [
      {
        type: 'button',
        icon: List,
        tooltip: t.value('toolbar.toc'),
        action: toggleToc,
        disabled: toc.value.length === 0,
        active: showToc.value,
      },
    ],
  },
  {
    items: [
      {
        type: 'button',
        icon: ChevronLeft,
        tooltip: t.value('toolbar.prev_page'),
        action: prevPage,
        disabled: currentChapter.value <= 1,
      },
      {
        type: 'text',
        content: `${currentChapter.value} / ${totalChapters.value}`,
        minWidth: '4rem',
      },
      {
        type: 'button',
        icon: ChevronRight,
        tooltip: t.value('toolbar.next_page'),
        action: nextPage,
        disabled: currentChapter.value >= totalChapters.value,
      },
    ],
  },
  {
    items: [
      {
        type: 'button',
        icon: isFullWidth.value ? Minimize2 : Maximize2,
        tooltip: isFullWidth.value ? t.value('toolbar.normal_width') : t.value('toolbar.full_width'),
        action: toggleFullWidth,
        active: isFullWidth.value,
      },
    ],
  },
];

defineExpose<RendererHandle>({
  getToolbarGroups,
  onToolbarChange: (listener) => emitter.subscribe(listener),
});

const loadEpub = async () => {
  if (!viewerRef.value) return;

  loading.value = true;
  error.value = null;
  toc.value = [];
  showToc.value = false;
  viewerRef.value.innerHTML = '';
  cleanup();

  try {
    let bookInput: string | ArrayBuffer = props.url;
    if (props.url.startsWith('blob:')) {
      const resp = await fetcher.value(props.url);
      bookInput = await resp.arrayBuffer();
    }

    book = ePub(bookInput) as unknown as BookLike;

    rendition = book.renderTo(viewerRef.value, {
      manager: 'continuous',
      flow: 'scrolled',
      width: '100%',
      height: '100%',
    });

    rendition.themes.register('default', {
      body: {
        background: '#ffffff !important',
        color: '#1a1a1a !important',
        'font-family': '"Noto Serif SC", "Source Han Serif SC", Georgia, "Times New Roman", serif !important',
        'font-size': '16px !important',
        'line-height': '2 !important',
        padding: '40px 60px !important',
        'max-width': '100% !important',
        'box-sizing': 'border-box !important',
        'word-break': 'break-word !important',
        'overflow-wrap': 'break-word !important',
      },
      p: { 'text-indent': '2em !important', margin: '0.8em 0 !important' },
      h1: { 'text-align': 'center !important', margin: '1.5em 0 1em !important' },
      h2: { margin: '1.2em 0 0.8em !important' },
      h3: { margin: '1em 0 0.6em !important' },
      img: { 'max-width': '100% !important', height: 'auto !important' },
      a: { color: '#2563eb !important', 'text-decoration': 'none !important' },
    });
    rendition.themes.select('default');

    await book.ready;

    // 异步生成 locations 索引
    book.locations.generate(1024).then(() => {
      if (!book) return;
      totalLocations = book.locations.length();
      const loc = rendition?.currentLocation() as { start?: { location?: number } } | undefined;
      const cur = loc?.start?.location ?? 0;
      currentChapter.value = cur + 1; totalChapters.value = totalLocations;
    }).catch(() => { /* ignore */ });

    const nav = await book.loaded.navigation as { toc?: TocItem[] };
    if (Array.isArray(nav?.toc)) {
      toc.value = nav.toc;
    }

    await rendition.display();

    loading.value = false;
    currentChapter.value = 1; totalChapters.value = totalLocations || 1;

    rendition.on('relocated', (location: unknown) => {
      const loc = location as { start?: { cfi?: string; location?: number; href?: string } };
      if (loc?.start?.cfi) {
        lastCfi = loc.start.cfi;
      }
      if (loc?.start?.href) {
        // 根据 spine href 查找匹配的 TOC 项
        const spineHref = loc.start.href;
        const matches: string[] = [];
        const collect = (items: TocItem[]) => {
          for (const item of items) {
            const base = item.href.split('#')[0];
            if (base && (spineHref === base || spineHref.endsWith('/' + base) || spineHref.endsWith(base))) {
              matches.push(item.href);
            }
            if (item.subitems) collect(item.subitems);
          }
        };
        collect(toc.value);
        if (matches.length === 1) {
          activeTocHref.value = matches[0];
        }
        // 多个匹配（同一文件不同 anchor）时保持当前选中（由点击设置）
      }
      const cur = loc?.start?.location;
      if (typeof cur === 'number' && totalLocations > 0) {
        currentChapter.value = cur + 1; totalChapters.value = totalLocations;
      }
    });
  } catch (err) {
    console.error('EPUB 加载错误:', err);
    error.value = t.value('epub.load_failed');
    loading.value = false;
  }
};

// 监听容器尺寸变化：等待 transition 完成后才 resize，避免 transition 期间频繁触发导致频闪
let resizeObserver: ResizeObserver | null = null;
let resizeTimeout: number | null = null;
let lastDimensions = { width: 0, height: 0 };
let isInitialResize = true;

const doResize = () => {
  if (!viewerRef.value || !rendition) return;
  rendition.resize(viewerRef.value.offsetWidth, viewerRef.value.offsetHeight);
  // resize 后恢复阅读位置
  if (lastCfi) {
    try { rendition.display(lastCfi); } catch { /* ignore */ }
  }
  // resize/display 可能重建 .epub-container，需要重新绑定滚动监听
  reattachScrollListener();
};

const setupResizeObserver = () => {
  if (!viewerRef.value) return;
  resizeObserver = new ResizeObserver(() => {
    if (!viewerRef.value) return;

    if (isInitialResize) {
      isInitialResize = false;
      lastDimensions = { width: viewerRef.value.offsetWidth, height: viewerRef.value.offsetHeight };
      return;
    }

    const newDimensions = { width: viewerRef.value.offsetWidth, height: viewerRef.value.offsetHeight };
    const widthDiff = Math.abs(lastDimensions.width - newDimensions.width);
    const heightDiff = Math.abs(lastDimensions.height - newDimensions.height);

    // 微小变化不触发，避免抖动
    if (widthDiff < 10 && heightDiff < 10) return;

    lastDimensions = newDimensions;

    // 防抖：等待 transition 完成（350ms）后才重新渲染
    if (resizeTimeout !== null) clearTimeout(resizeTimeout);
    resizeTimeout = window.setTimeout(doResize, 350);
  });
  resizeObserver.observe(viewerRef.value);
};

// 监听 epub-container 滚动，接近底部时强制加载后续 section
let scrollContainer: Element | null = null;
const onContainerScroll = () => {
  if (!scrollContainer) return;
  const el = scrollContainer as HTMLElement;
  if (el.scrollTop + el.clientHeight >= el.scrollHeight - 200) {
    try {
      const mgr = (rendition as unknown as { manager?: { check?: (t?: number, e?: number) => Promise<unknown> } })?.manager;
      // 传递垂直偏移量参数，让 check() 在接近底部时就触发加载下一节
      mgr?.check?.(500, 500);
    } catch { /* ignore */ }
  }
};

const reattachScrollListener = () => {
  // 清理旧监听
  if (scrollContainer) {
    scrollContainer.removeEventListener('scroll', onContainerScroll);
    scrollContainer = null;
  }
  const tryAttach = () => {
    scrollContainer = viewerRef.value?.querySelector('.epub-container') ?? null;
    if (scrollContainer) {
      scrollContainer.addEventListener('scroll', onContainerScroll, { passive: true });
    } else {
      requestAnimationFrame(tryAttach);
    }
  };
  requestAnimationFrame(tryAttach);
};

onMounted(() => {
  loadEpub();
  setupResizeObserver();
  reattachScrollListener();
});

watch(() => props.url, (newUrl) => {
  // 只有 URL 有效时才加载（避免空字符串或已 revoke 的 blob URL）
  if (newUrl) loadEpub();
});

onBeforeUnmount(() => {
  if (resizeObserver) resizeObserver.disconnect();
  if (resizeTimeout !== null) clearTimeout(resizeTimeout);
  scrollContainer?.removeEventListener('scroll', onContainerScroll);
  cleanup();
});
</script>

<template>
  <div class="pio-relative pio-w-full pio-h-full pio-flex pio-justify-center pio-bg-surface-1 pio-overflow-hidden">
    <RendererError v-if="error" :message="error" class="pio-absolute pio-inset-0" />

    <div
      v-if="loading && !error"
      class="pio-absolute pio-inset-0 pio-flex pio-items-center pio-justify-center pio-z-10"
    >
      <div class="pio-w-12 pio-h-12 pio-border-4 pio-border-line-strong pio-border-t-spinner-head pio-rounded-full pio-animate-spin" />
    </div>

    <!-- 目录侧栏 - 滑入动画 -->
    <div
      v-if="toc.length > 0"
      class="pio-absolute pio-inset-0 pio-z-20 pio-flex"
      :style="{ opacity: showToc ? 1 : 0, pointerEvents: showToc ? 'auto' : 'none', transition: 'opacity 0.3s' }"
    >
      <div
        class="pio-w-72 pio-h-full pio-flex pio-flex-col"
        :style="{
          maxWidth: '80%',
          background: 'rgba(0,0,0,0.9)',
          backdropFilter: 'blur(12px)',
          borderRight: '1px solid rgba(255,255,255,0.1)',
          boxShadow: '0 25px 50px -12px rgba(0,0,0,0.25)',
          transform: showToc ? 'translateX(0)' : 'translateX(-100%)',
          transition: 'transform 0.3s ease',
        }"
      >
        <div class="pio-flex pio-items-center pio-justify-between pio-flex-shrink-0" style="padding: 12px 16px; border-bottom: 1px solid rgba(255,255,255,0.1)">
          <span style="color: white; font-weight: 500; font-size: 14px">{{ t('toolbar.toc') }}</span>
          <button style="color: rgba(255,255,255,0.6); background: none; border: none; cursor: pointer; padding: 4px" @click="showToc = false">
            <X style="width: 16px; height: 16px" />
          </button>
        </div>
        <div class="pio-flex-1 pio-overflow-y-auto" style="padding: 8px 4px">
          <template v-for="(item, i) in toc" :key="`${item.href}-${i}`">
            <button
              :style="{
                width: '100%', textAlign: 'left', padding: '8px 12px', fontSize: '14px',
                color: isActive(item.href) ? 'white' : 'rgba(255,255,255,0.7)',
                fontWeight: isActive(item.href) ? '500' : '400',
                background: isActive(item.href) ? 'rgba(255,255,255,0.15)' : 'none',
                border: 'none', cursor: 'pointer', borderRadius: '4px',
                overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', display: 'block',
                transition: 'all 0.15s',
              }"
              :title="item.label"
              @click="handleTocClick(item.href)"
              @mouseenter="!isActive(item.href) && (($event.target as HTMLElement).style.background = 'rgba(255,255,255,0.1)')"
              @mouseleave="!isActive(item.href) && (($event.target as HTMLElement).style.background = 'none')"
            >
              {{ item.label.trim() }}
            </button>
            <template v-if="item.subitems && item.subitems.length > 0">
              <button
                v-for="(sub, j) in item.subitems"
                :key="`${sub.href}-${j}`"
                :style="{
                  width: '100%', textAlign: 'left', padding: '8px 12px 8px 28px', fontSize: '13px',
                  color: isActive(sub.href) ? 'white' : 'rgba(255,255,255,0.6)',
                  fontWeight: isActive(sub.href) ? '500' : '400',
                  background: isActive(sub.href) ? 'rgba(255,255,255,0.15)' : 'none',
                  border: 'none', cursor: 'pointer', borderRadius: '4px',
                  overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', display: 'block',
                  transition: 'all 0.15s',
                }"
                :title="sub.label"
                @click="handleTocClick(sub.href)"
                @mouseenter="!isActive(sub.href) && (($event.target as HTMLElement).style.background = 'rgba(255,255,255,0.1)')"
                @mouseleave="!isActive(sub.href) && (($event.target as HTMLElement).style.background = 'none')"
              >
                {{ sub.label.trim() }}
              </button>
            </template>
          </template>
        </div>
      </div>
      <div
        class="pio-flex-1"
        :style="{ background: showToc ? 'rgba(0,0,0,0.3)' : 'transparent', transition: 'background 0.3s' }"
        @click="showToc = false"
      />
    </div>

    <div
      v-if="!error"
      ref="viewerRef"
      class="pio-h-full pio-bg-surface-toolbar"
      :style="{
        width: isFullWidth ? '100%' : `${A4_WIDTH}px`,
        maxWidth: '100%',
        transition: 'width 0.3s ease',
        boxShadow: '0 1px 3px rgba(0,0,0,0.12)',
        overflow: 'hidden',
      }"
    />
  </div>
</template>

<style>
.epub-container { overflow-y: auto !important; scrollbar-width: thin; }
.epub-container::-webkit-scrollbar { width: 8px; }
.epub-container::-webkit-scrollbar-track { background: transparent; }
.epub-container::-webkit-scrollbar-thumb { background: rgba(0,0,0,0.15); border-radius: 4px; }
.epub-container::-webkit-scrollbar-thumb:hover { background: rgba(0,0,0,0.3); }
.epub-view > iframe { background: white; }
</style>

// packages/react/src/renderers/Epub/index.tsx
import { useEffect, useRef, useState, useCallback, useImperativeHandle, forwardRef } from 'react';
import ePub from '@likecoin/epub-ts';
import { X, ChevronLeft, ChevronRight, Maximize2, Minimize2, List } from 'lucide-react';
import { useTranslator } from '../../i18n/LocaleContext';
import { useFetcher } from '../../RequestContext';
import { RendererError } from '../RendererError';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';

// 全局注入 epubjs 容器样式（只注入一次）
if (typeof document !== 'undefined' && !document.getElementById('pio-epub-styles')) {
  const styleEl = document.createElement('style');
  styleEl.id = 'pio-epub-styles';
  styleEl.textContent = `
    .epub-container { overflow-y: auto !important; scrollbar-width: thin; }
    .epub-container::-webkit-scrollbar { width: 8px; }
    .epub-container::-webkit-scrollbar-track { background: transparent; }
    .epub-container::-webkit-scrollbar-thumb { background: rgba(0,0,0,0.15); border-radius: 4px; }
    .epub-container::-webkit-scrollbar-thumb:hover { background: rgba(0,0,0,0.3); }
    .epub-view > iframe { background: white; }
  `;
  document.head.appendChild(styleEl);
}

export interface TocItem {
  label: string;
  href: string;
  subitems?: TocItem[];
}

export interface EpubRendererHandle extends RendererHandle {
  prevPage: () => void;
  nextPage: () => void;
  toggleFullWidth: () => void;
  toggleToc: () => void;
}

interface EpubRendererProps {
  url: string;
}

interface RenditionLike {
  display: (target?: string) => Promise<unknown>;
  next: () => Promise<unknown>;
  prev: () => Promise<unknown>;
  on: (event: string, cb: (...args: unknown[]) => void) => void;
  resize: (width: number, height: number) => void;
  currentLocation: () => unknown;
  destroy?: () => void;
  themes: {
    register: (name: string, styles: Record<string, unknown>) => void;
    select: (name: string) => void;
  };
}

interface BookLike {
  ready: Promise<unknown>;
  loaded: { navigation: Promise<unknown> };
  locations: {
    generate: (chars: number) => Promise<string[]>;
    length: () => number;
    locationFromCfi: (cfi: string) => number;
  };
  renderTo: (el: HTMLElement, opts: Record<string, unknown>) => RenditionLike;
  destroy: () => void;
}

const A4_WIDTH = 794;

export const EpubRenderer = forwardRef<EpubRendererHandle, EpubRendererProps>(
  ({ url }, ref) => {
    const t = useTranslator();
    const fetcher = useFetcher();
    const viewerRef = useRef<HTMLDivElement>(null);
    const bookRef = useRef<BookLike | null>(null);
    const renditionRef = useRef<RenditionLike | null>(null);

    const totalLocationsRef = useRef(0);
    const lastCfiRef = useRef<string | null>(null);
    const isFullWidthRef = useRef(false);

    // 内部状态管理
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [isFullWidth, setIsFullWidth] = useState(false);
    const [toc, setToc] = useState<TocItem[]>([]);
    const [showToc, setShowToc] = useState(false);
    const [activeTocHref, setActiveTocHref] = useState<string>('');
    const [currentChapter, setCurrentChapter] = useState(0);
    const [totalChapters, setTotalChapters] = useState(0);
    const tocRef = useRef<TocItem[]>([]);
    tocRef.current = toc;

    isFullWidthRef.current = isFullWidth;

    // 事件发射器：用于通知主组件工具栏状态变化
    const listenersRef = useRef<Set<() => void>>(new Set());
    const notifyToolbarChange = useCallback(() => {
      listenersRef.current.forEach(listener => listener());
    }, []);

    // 监听影响工具栏的状态变化
    useEffect(() => {
      notifyToolbarChange();
    }, [currentChapter, notifyToolbarChange]);

    useEffect(() => {
      notifyToolbarChange();
    }, [totalChapters, notifyToolbarChange]);

    useEffect(() => {
      notifyToolbarChange();
    }, [isFullWidth, notifyToolbarChange]);

    useEffect(() => {
      notifyToolbarChange();
    }, [toc.length, notifyToolbarChange]);

    const handlePrev = useCallback(() => {
      renditionRef.current?.prev();
    }, []);

    const handleNext = useCallback(() => {
      renditionRef.current?.next();
    }, []);

    // 滚动监听：接近底部时强制触发 check 加载后续 section
    const scrollContainerRef = useRef<Element | null>(null);
    const scrollRafRef = useRef(0);

    const onScrollRef = useRef((_e?: Event) => {
      const container = scrollContainerRef.current;
      if (!container) return;
      const el = container as HTMLElement;
      const nearBottom = el.scrollTop + el.clientHeight >= el.scrollHeight - 200;
      if (nearBottom) {
        try {
          const mgr = (renditionRef.current as unknown as { manager?: { check?: (t?: number, e?: number) => Promise<unknown> } })?.manager;
          mgr?.check?.(500, 500);
        } catch { /* ignore */ }
      }
    });

    const reattachScrollListener = useCallback(() => {
      // 清理旧监听
      if (scrollContainerRef.current) {
        scrollContainerRef.current.removeEventListener('scroll', onScrollRef.current);
        scrollContainerRef.current = null;
      }
      cancelAnimationFrame(scrollRafRef.current);

      const tryAttach = () => {
        const container = viewerRef.current?.querySelector('.epub-container') ?? null;
        if (!container) {
          scrollRafRef.current = requestAnimationFrame(tryAttach);
          return;
        }
        scrollContainerRef.current = container;
        container.addEventListener('scroll', onScrollRef.current, { passive: true });
      };
      scrollRafRef.current = requestAnimationFrame(tryAttach);
    }, []);

    const toggleFullWidth = useCallback(() => {
      const newVal = !isFullWidthRef.current;
      setIsFullWidth(newVal);
      // 等 CSS transition 完成后再 resize 并恢复位置
      setTimeout(() => {
        const viewer = viewerRef.current;
        const rendition = renditionRef.current;
        if (!viewer || !rendition) return;
        rendition.resize(viewer.offsetWidth, viewer.offsetHeight);
        // 重排后恢复阅读位置
        if (lastCfiRef.current) {
          rendition.display(lastCfiRef.current);
        }
        // resize/display 可能重建 .epub-container，需要重新绑定滚动监听
        reattachScrollListener();
      }, 350);
    }, [reattachScrollListener]);

    const toggleToc = useCallback(() => {
      setShowToc(prev => !prev);
    }, []);

    const handleTocClick = useCallback((href: string) => {
      setActiveTocHref(href);
      renditionRef.current?.display(href);
      setShowToc(false);
    }, []);

    // 工具栏配置
    const getToolbarGroups = useCallback((): ToolbarGroup[] => [
      {
        items: [
          { type: 'button', icon: <List className="pio-w-4 pio-h-4" />, tooltip: t('toolbar.toc'), action: toggleToc, disabled: toc.length === 0, active: showToc },
        ],
      },
      {
        items: [
          { type: 'button', icon: <ChevronLeft className="pio-w-4 pio-h-4" />, tooltip: t('toolbar.prev_page'), action: handlePrev, disabled: currentChapter <= 1 },
          { type: 'text', content: `${currentChapter} / ${totalChapters}`, minWidth: '4rem' },
          { type: 'button', icon: <ChevronRight className="pio-w-4 pio-h-4" />, tooltip: t('toolbar.next_page'), action: handleNext, disabled: currentChapter >= totalChapters },
        ],
      },
      {
        items: [
          { type: 'button', icon: isFullWidth ? <Minimize2 className="pio-w-4 pio-h-4" /> : <Maximize2 className="pio-w-4 pio-h-4" />, tooltip: isFullWidth ? t('toolbar.normal_width') : t('toolbar.full_width'), action: toggleFullWidth, active: isFullWidth },
        ],
      },
    ], [currentChapter, totalChapters, isFullWidth, showToc, toc.length, t, handlePrev, handleNext, toggleToc, toggleFullWidth]);

    useImperativeHandle(ref, () => ({
      getToolbarGroups,
      onToolbarChange: (listener: () => void) => {
        listenersRef.current.add(listener);
        return () => listenersRef.current.delete(listener);
      },
      prevPage: handlePrev,
      nextPage: handleNext,
      toggleFullWidth,
      toggleToc,
    }), [getToolbarGroups, handlePrev, handleNext, toggleFullWidth, toggleToc]);

    useEffect(() => {
      const viewer = viewerRef.current;
      // 只有 URL 有效时才加载（避免空字符串或已 revoke 的 blob URL）
      if (!viewer || !url) return;

      setLoading(true);
      setError(null);
      setToc([]);
      setShowToc(false);
      viewer.innerHTML = '';
      lastCfiRef.current = null;
      totalLocationsRef.current = 0;

      let cancelled = false;
      // StrictMode 下 effect 会立即 mount→unmount→mount
      // 用 microtask 延迟初始化，让第一次的 cleanup 先执行，避免 epubjs 内部状态被污染
      const loadTimer = window.setTimeout(() => {
        if (cancelled) return;
        load();
      }, 0);

      const load = async () => {
        try {
          let bookInput: string | ArrayBuffer = url;
          if (url.startsWith('blob:')) {
            const resp = await fetcher(url);
            bookInput = await resp.arrayBuffer();
          }

          const book = ePub(bookInput) as unknown as BookLike;
          bookRef.current = book;

          const rendition = book.renderTo(viewer, {
            manager: 'continuous',
            flow: 'scrolled',
            width: '100%',
            height: '100%',
          });
          renditionRef.current = rendition;

          rendition.themes.register('default', {
            body: {
              background: '#ffffff !important',
              color: '#1a1a1a !important',
              'font-family': '"Noto Serif SC", "Source Han Serif SC", Georgia, "Times New Roman", serif !important',
              'font-size': '16px !important',
              'line-height': '2 !important',
              padding: '40px 60px !important',
              'max-width': '100% !important',
              'box-sizing': 'border-box !important',
              'word-break': 'break-word !important',
              'overflow-wrap': 'break-word !important',
            },
            p: { 'text-indent': '2em !important', margin: '0.8em 0 !important' },
            h1: { 'text-align': 'center !important', margin: '1.5em 0 1em !important' },
            h2: { margin: '1.2em 0 0.8em !important' },
            h3: { margin: '1em 0 0.6em !important' },
            img: { 'max-width': '100% !important', height: 'auto !important' },
            a: { color: '#2563eb !important', 'text-decoration': 'none !important' },
          });
          rendition.themes.select('default');

          await book.ready;

          // 异步生成 locations 索引（用于实时页数）
          book.locations.generate(1024).then(() => {
            if (cancelled) return;
            totalLocationsRef.current = book.locations.length();
            // 更新内部状态
            const loc = renditionRef.current?.currentLocation() as { start?: { location?: number; cfi?: string } } | undefined;
            const cur = loc?.start?.location ?? 0;
            setCurrentChapter(cur + 1);
            setTotalChapters(totalLocationsRef.current);
          }).catch(() => { /* ignore */ });

          // 获取目录
          const nav = await book.loaded.navigation as { toc?: TocItem[] };
          if (!cancelled && Array.isArray(nav?.toc)) {
            setToc(nav.toc);
          }

          await rendition.display();

          if (cancelled) return;
          setCurrentChapter(1);
          setTotalChapters(totalLocationsRef.current || 1);

          setLoading(false);

          rendition.on('relocated', (location: unknown) => {
            const loc = location as { start?: { cfi?: string; location?: number; href?: string } };
            if (loc?.start?.cfi) {
              lastCfiRef.current = loc.start.cfi;
            }
            if (loc?.start?.href) {
              // 根据 spine href 查找匹配的 TOC 项
              const spineHref = loc.start.href;
              const matches: string[] = [];
              const collect = (items: TocItem[]) => {
                for (const item of items) {
                  const base = item.href.split('#')[0];
                  if (base && (spineHref === base || spineHref.endsWith('/' + base) || spineHref.endsWith(base))) {
                    matches.push(item.href);
                  }
                  if (item.subitems) collect(item.subitems);
                }
              };
              collect(tocRef.current);
              if (matches.length === 1) {
                // 唯一匹配，直接设置
                setActiveTocHref(matches[0]);
              }
              // 多个匹配（同一文件不同 anchor）时保持当前选中（由点击设置）
            }
            const cur = loc?.start?.location;
            const total = totalLocationsRef.current;
            if (typeof cur === 'number' && total > 0) {
              setCurrentChapter(cur + 1);
              setTotalChapters(total);
            }
          });

        } catch (err) {
          console.error('EPUB 加载错误:', err);
          if (!cancelled) {
            setError(t('epub.load_failed'));
            setLoading(false);
          }
        }
      };

      return () => {
        cancelled = true;
        window.clearTimeout(loadTimer);
        try { renditionRef.current?.destroy?.(); } catch { /* ignore */ }
        try { bookRef.current?.destroy(); } catch { /* ignore */ }
        renditionRef.current = null;
        bookRef.current = null;
      };
    }, [url]);

    // 监听容器尺寸变化：等待 transition 完成后才 resize，避免 transition 期间频繁触发导致频闪
    useEffect(() => {
      const viewer = viewerRef.current;
      if (!viewer) return;

      let isInitialRender = true;
      let lastDimensions = { width: 0, height: 0 };
      let resizeTimeout: number | null = null;

      const doResize = () => {
        const v = viewerRef.current;
        const rendition = renditionRef.current;
        if (!v || !rendition) return;
        rendition.resize(v.offsetWidth, v.offsetHeight);
        // resize 后恢复阅读位置
        if (lastCfiRef.current) {
          try { rendition.display(lastCfiRef.current); } catch { /* ignore */ }
        }
        // resize/display 可能重建 .epub-container，需要重新绑定滚动监听
        reattachScrollListener();
      };

      const observer = new ResizeObserver(() => {
        const v = viewerRef.current;
        if (!v) return;

        if (isInitialRender) {
          isInitialRender = false;
          lastDimensions = { width: v.offsetWidth, height: v.offsetHeight };
          return;
        }

        const newDimensions = { width: v.offsetWidth, height: v.offsetHeight };
        const widthDiff = Math.abs(lastDimensions.width - newDimensions.width);
        const heightDiff = Math.abs(lastDimensions.height - newDimensions.height);

        // 微小变化不触发，避免抖动
        if (widthDiff < 10 && heightDiff < 10) return;

        lastDimensions = newDimensions;

        // 防抖：等待 transition 完成（350ms）后才重新渲染
        if (resizeTimeout !== null) clearTimeout(resizeTimeout);
        resizeTimeout = window.setTimeout(() => {
          doResize();
        }, 350);
      });

      observer.observe(viewer);

      return () => {
        observer.disconnect();
        if (resizeTimeout !== null) clearTimeout(resizeTimeout);
      };
    }, [reattachScrollListener]);

    useEffect(() => {
      reattachScrollListener();
      return () => {
        cancelAnimationFrame(scrollRafRef.current);
        scrollContainerRef.current?.removeEventListener('scroll', onScrollRef.current);
      };
    }, [url, reattachScrollListener]);

    const isActive = useCallback((href: string) => {
      return href === activeTocHref;
    }, [activeTocHref]);

    const renderTocItems = (items: TocItem[], depth = 0) => (
      <ul style={{ marginLeft: depth > 0 ? 16 : 0 }}>
        {items.map((item, i) => {
          const active = isActive(item.href);
          return (
            <li key={`${item.href}-${i}`}>
              <button
                onClick={() => handleTocClick(item.href)}
                className={`pio-w-full pio-text-left pio-py-2 pio-px-3 pio-text-sm pio-rounded pio-transition-all pio-truncate ${active
                    ? 'pio-text-fg-primary pio-bg-surface-3 pio-font-medium'
                    : 'pio-text-fg-secondary hover:pio-text-fg-primary hover:pio-bg-surface-2'
                  }`}
                title={item.label}
              >
                {item.label.trim()}
              </button>
              {item.subitems && item.subitems.length > 0 && renderTocItems(item.subitems, depth + 1)}
            </li>
          );
        })}
      </ul>
    );

    return (
      <div className="pio-relative pio-w-full pio-h-full pio-flex pio-justify-center pio-bg-surface-1 pio-overflow-hidden">
        {error && <RendererError message={error} />}

        {loading && !error && (
          <div className="pio-absolute pio-inset-0 pio-flex pio-items-center pio-justify-center pio-z-10">
            <div className="pio-w-12 pio-h-12 pio-border-4 pio-border-line-strong pio-border-t-spinner-head pio-rounded-full pio-animate-spin" />
          </div>
        )}

        {/* 目录侧栏 - 滑入动画 */}
        {toc.length > 0 && (
          <div
            className="pio-absolute pio-inset-0 pio-z-20 pio-flex pio-transition-opacity pio-duration-300"
            style={{
              opacity: showToc ? 1 : 0,
              pointerEvents: showToc ? 'auto' : 'none',
            }}
          >
            <div
              className="pio-w-72 pio-max-w-[80%] pio-h-full pio-bg-surface-overlay pio-backdrop-blur-xl pio-border-r pio-border-line-weak pio-flex pio-flex-col pio-shadow-2xl pio-transition-transform pio-duration-300"
              style={{ transform: showToc ? 'translateX(0)' : 'translateX(-100%)' }}
            >
              <div className="pio-flex pio-items-center pio-justify-between pio-px-4 pio-py-3 pio-border-b pio-border-line-weak pio-flex-shrink-0">
                <span className="pio-text-fg-primary pio-font-medium pio-text-sm">{t('toolbar.toc')}</span>
                <button
                  onClick={() => setShowToc(false)}
                  className="pio-text-fg-tertiary hover:pio-text-fg-primary pio-transition-colors"
                >
                  <X className="pio-w-4 pio-h-4" />
                </button>
              </div>
              <div className="pio-flex-1 pio-overflow-y-auto pio-py-4 pio-px-1">
                {renderTocItems(toc)}
              </div>
            </div>
            <div
              className="pio-flex-1 pio-transition-opacity pio-duration-300"
              style={{ background: showToc ? 'rgba(0,0,0,0.3)' : 'transparent' }}
              onClick={() => setShowToc(false)}
            />
          </div>
        )}

        {!error && (
          <div
            ref={viewerRef}
            className="pio-h-full pio-bg-surface-toolbar pio-shadow-lg"
            style={{
              width: isFullWidth ? '100%' : `${A4_WIDTH}px`,
              maxWidth: '100%',
              transition: 'width 0.3s ease',
              overflow: 'hidden',
            }}
          />
        )}
      </div>
    );
  }
);
