// packages/react/src/PioneerContent.tsx
import React, { useCallback, useMemo, useRef, useState, useEffect } from 'react';
import { getFileType, createTranslator, resolveShowClose, type Locale, type Messages, type Translator, type Theme, downloadFileWithFetcher, type WatermarkConfig } from '@pioneer/core';
import { LocaleProvider } from './i18n/LocaleContext';
import { ThemeProvider } from './ThemeContext';
import type { PreviewFileInput, CustomRenderer, CustomRendererContext } from './types';
import type { CustomRendererEventPayload, PreviewFile, RequestHandler, RequestInitFactory, ShouldFetchAsBlob, SearchOptions, SearchResult } from '@pioneer/core';
import { normalizeFiles } from './utils/fileNormalizer';
import { RequestProvider, useResolvedUrl, useFetcher } from './RequestContext';
import type { RendererHandle } from './renderers/base.types';
import type { ToolbarGroup } from './renderers/toolbar.types';
import { UnsupportedRenderer } from './renderers/Unsupported';
import { WatermarkOverlay } from './components/WatermarkOverlay';
import { SearchPanel } from './components/SearchPanel';
import {
  useKeyboardNavigation,
  useThemeMode,
} from './hooks';
import { PioneerToolbar, PioneerRenderer, NavArrows } from './components/preview';
import { BUILTIN_RENDERERS } from './renderers/registry';

const MAX_ZIP_NESTING_DEPTH = 3;

export interface PioneerContentProps {
  files: PreviewFileInput[];
  currentIndex: number;
  onNavigate?: (index: number) => void;
  customRenderers?: CustomRenderer[];
  mode?: 'modal' | 'embed';
  onClose?: () => void;
  zipNestingDepth?: number;
  locale?: Locale;
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  headless?: boolean;
  theme?: Theme;
  onCustomEvent?: (event: CustomRendererEventPayload) => void;
  requestInit?: RequestInitFactory;
  requestHandler?: RequestHandler;
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  onDownload?: (file: PreviewFile) => void;
  onError?: (error: Error, errorInfo: React.ErrorInfo) => void;
  /** 是否显示关闭按钮，默认根据 mode 决定（modal: true, embed: false） */
  showClose?: boolean;
  showDownload?: boolean;
  /** 水印配置 */
  watermark?: WatermarkConfig;
  /** 加密文件密码（跳过密码弹窗直接加载） */
  password?: string;
}

export const PioneerContent: React.FC<PioneerContentProps> = (props) => {
  const { requestInit, requestHandler, shouldFetchAsBlob } = props;
  return (
    <RequestProvider
      requestInit={requestInit}
      requestHandler={requestHandler}
      shouldFetchAsBlob={shouldFetchAsBlob}
    >
      <PioneerContentInner {...props} />
    </RequestProvider>
  );
};

const PioneerContentInner: React.FC<PioneerContentProps> = ({
  files,
  currentIndex,
  onNavigate,
  customRenderers = [],
  mode = 'modal',
  onClose,
  zipNestingDepth = 0,
  locale = 'zh-CN',
  messages: userMessages,
  headless = false,
  theme = 'dark',
  onCustomEvent,
  onDownload,
  onError,
  showClose,
  showDownload = true,
  watermark,
  password,
  requestInit: _requestInit,
  requestHandler: _requestHandler,
  shouldFetchAsBlob: _shouldFetchAsBlob,
}) => {
  const t: Translator = useMemo(
    () => createTranslator({ locale, messages: userMessages }),
    [locale, userMessages],
  );

  const normalizedFiles = useMemo(() => normalizeFiles(files), [files]);
  const currentFile = normalizedFiles[currentIndex];
  const resolvedUrl = useResolvedUrl(currentFile);
  const fetcher = useFetcher();

  const customRenderer = useMemo(() => {
    if (!currentFile) return null;
    return customRenderers.find(renderer => renderer.test(currentFile));
  }, [currentFile, customRenderers]);

  const fileType = currentFile ? getFileType(currentFile) : 'unsupported';

  // 主题
  const resolvedTheme = useThemeMode(theme);

  // Refs
  const contentRef = useRef<HTMLDivElement>(null);
  const rootRef = useRef<HTMLDivElement>(null);

  // 新架构：通用渲染器 ref，用于获取工具栏配置
  const rendererInstanceRef = useRef<RendererHandle | null>(null);
  const [rendererToolbarGroups, setRendererToolbarGroups] = useState<ToolbarGroup[]>([]);
  const cleanupRef = useRef<(() => void) | null>(null);

  // 搜索状态
  const [searchOpen, setSearchOpen] = useState(false);
  const [searchResults, setSearchResults] = useState<SearchResult>({ total: 0, current: -1, matches: [] });
  const [searchQuery, setSearchQuery] = useState('');
  const [searchCaseSensitive, setSearchCaseSensitive] = useState(false);
  void searchQuery; void searchCaseSensitive;
  void setSearchResults;

  // 设置渲染器并初始化工具栏（在渲染器挂载/更新时同步触发）
  const setupRenderer = useCallback((renderer: RendererHandle | null) => {
    // 清理旧的订阅
    if (cleanupRef.current) {
      cleanupRef.current();
      cleanupRef.current = null;
    }

    rendererInstanceRef.current = renderer;

    if (!renderer?.getToolbarGroups) {
      setRendererToolbarGroups([]);
      return;
    }

    // 立即获取一次初始状态
    const initialGroups = renderer.getToolbarGroups();
    setRendererToolbarGroups(initialGroups);

    // 如果渲染器支持事件订阅，使用事件机制
    if (renderer.onToolbarChange) {
      const unsubscribe = renderer.onToolbarChange(() => {
        const groups = renderer.getToolbarGroups();
        setRendererToolbarGroups(groups);
      });

      cleanupRef.current = unsubscribe;
      return;
    }

    // 回退机制：如果渲染器不支持事件，使用轮询
    const interval = setInterval(() => {
      const groups = renderer.getToolbarGroups();
      setRendererToolbarGroups(groups);
    }, 100);
    cleanupRef.current = () => clearInterval(interval);
  }, []);

  // Callback ref：在渲染器挂载/卸载时立即触发
  const rendererRef = useCallback((renderer: RendererHandle | null) => {
    setupRenderer(renderer);
  }, [setupRenderer]);

  // 组件卸载时清理
  useEffect(() => {
    return () => {
      if (cleanupRef.current) {
        cleanupRef.current();
        cleanupRef.current = null;
      }
    };
  }, []);

  // 键盘导航
  useKeyboardNavigation({
    mode,
    currentIndex,
    totalFiles: normalizedFiles.length,
    onNavigate,
    onClose,
    rootRef,
  });

  // 搜索相关事件处理
  const handleSearch = useCallback(async (query: string, options: SearchOptions) => {
    const renderer = rendererInstanceRef.current;
    if (!renderer || !renderer.search || !query.trim()) {
      setSearchResults({ total: 0, current: -1, matches: [] });
      return;
    }
    try {
      const result = await renderer.search(query, { ...options, caseSensitive: options.caseSensitive ?? false });
      setSearchResults(result);
    } catch {
      setSearchResults({ total: 0, current: -1, matches: [] });
    }
  }, []);

  const handleSearchPrev = useCallback(() => {
    rendererInstanceRef.current?.goToPrevMatch?.();
  }, []);

  const handleSearchNext = useCallback(() => {
    rendererInstanceRef.current?.goToNextMatch?.();
  }, []);

  const handleSearchClose = useCallback(() => {
    setSearchOpen(false);
    rendererInstanceRef.current?.clearSearch?.();
    setSearchResults({ total: 0, current: -1, matches: [] });
    setSearchQuery('');
  }, []);

  const handleSearchOpen = useCallback(() => {
    setSearchOpen(true);
  }, []);

  // Ctrl+F / Cmd+F 快捷键
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const isCtrlF = (e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'f';
      if (isCtrlF) {
        e.preventDefault();
        handleSearchOpen();
      }
    };

    if (mode === 'modal') {
      window.addEventListener('keydown', handleKeyDown);
      return () => window.removeEventListener('keydown', handleKeyDown);
    } else {
      const el = rootRef.current;
      if (el) {
        el.addEventListener('keydown', handleKeyDown);
        return () => el.removeEventListener('keydown', handleKeyDown);
      }
    }
  }, [mode, rootRef, handleSearchOpen]);

  // 图片自动适应窗口（已禁用，改为手动点击"适应窗口"按钮）
  // useImageAutoFit({
  //   enabled: fileType === 'image',
  //   naturalWidth: state.image.naturalWidth,
  //   naturalHeight: state.image.naturalHeight,
  //   containerRef: contentRef,
  //   onZoomChange: (zoom) => dispatch({ type: 'SET_ZOOM', payload: zoom }),
  // });

  // 自定义渲染器上下文
  const emitCustom = useCallback(
    (name: string, payload?: unknown) => {
      if (!currentFile) return;
      onCustomEvent?.({ name, payload, file: currentFile });
    },
    [currentFile, onCustomEvent],
  );

  const customCtx = useMemo<CustomRendererContext>(
    () => ({ emit: emitCustom, t, theme: resolvedTheme, locale }),
    [emitCustom, t, resolvedTheme, locale],
  );

  const handleDownload = useCallback(async () => {
    if (!currentFile) return;
    if (onDownload) {
      await onDownload(currentFile);
      return;
    }
    try {
      await downloadFileWithFetcher(currentFile.url, currentFile.name, fetcher);
    } catch (err) {
      console.error('[pioneer] download failed:', err);
    }
  }, [currentFile, onDownload, fetcher]);

  if (!currentFile) return null;

  return (
    <LocaleProvider locale={locale} messages={userMessages}>
      <ThemeProvider theme={resolvedTheme}>
        <div
          ref={rootRef}
          tabIndex={mode === 'embed' ? 0 : -1}
          data-theme={resolvedTheme}
          className="pio-relative pio-w-full pio-h-full pio-flex pio-flex-col pio-overflow-hidden pio-outline-none"
        >
          {!headless && (
            <PioneerToolbar
              fileName={currentFile.name}
              currentIndex={currentIndex}
              totalFiles={normalizedFiles.length}
              toolGroups={rendererToolbarGroups}
              t={t}
              onDownload={handleDownload}
              onClose={onClose}
              showClose={resolveShowClose(mode, showClose)}
              showDownload={showDownload}
            />
          )}

          {/* 搜索面板：位于工具栏下方，搜索激活时显示 */}
          {!headless && searchOpen && (
            <SearchPanel
              t={t}
              onClose={handleSearchClose}
              onSearch={(query, options) => {
                setSearchQuery(query);
                setSearchCaseSensitive(options.caseSensitive);
                handleSearch(query, options);
              }}
              onPrevMatch={handleSearchPrev}
              onNextMatch={handleSearchNext}
              matchCount={searchResults.current}
              totalCount={searchResults.total}
            />
          )}

          <div
            ref={contentRef}
            className="pio-relative pio-flex-1 pio-flex pio-items-center pio-justify-center pio-overflow-hidden"
          >
            <PioneerRenderer
              currentFile={currentFile}
              customRenderer={customRenderer}
              customRendererContext={customCtx}
              t={t}
              onDownload={handleDownload}
              onError={onError}
            >
              {(() => {
                // ZIP 嵌套深度超限：fallback 到 Unsupported
                if (fileType === 'zip' && zipNestingDepth >= MAX_ZIP_NESTING_DEPTH) {
                  return (
                    <UnsupportedRenderer
                      fileName={currentFile.name}
                      fileType={currentFile.type}
                      onDownload={handleDownload}
                    />
                  );
                }

                // 从注册表查找匹配的渲染器
                const rendererConfig = BUILTIN_RENDERERS.find(
                  (r) => r.fileType === fileType,
                );

                if (rendererConfig) {
                  const RendererComponent = rendererConfig.component;
                  const rendererProps = rendererConfig.getProps({
                    resolvedUrl,
                    zipNestingDepth,
                    currentFile,
                    password,
                    onPasswordError: undefined,
                  });
                  return <RendererComponent ref={rendererRef} {...rendererProps} />;
                }

                // 未匹配：fallback 到 UnsupportedRenderer
                return (
                  <UnsupportedRenderer
                    fileName={currentFile.name}
                    fileType={currentFile.type}
                    onDownload={handleDownload}
                  />
                );
              })()}
            </PioneerRenderer>

            {/* 水印层：位于渲染器内容之上，pointer-events: none 不干扰交互 */}
            {!headless && watermark && (
              <WatermarkOverlay config={watermark} containerRef={contentRef} theme={resolvedTheme} />
            )}
          </div>

          {!headless && normalizedFiles.length > 1 && (
            <NavArrows
              containerRef={contentRef}
              hasPrev={currentIndex > 0}
              hasNext={currentIndex < normalizedFiles.length - 1}
              onPrev={() => onNavigate?.(currentIndex - 1)}
              onNext={() => onNavigate?.(currentIndex + 1)}
              resetKey={currentIndex}
              t={t}
            />
          )}
        </div>
      </ThemeProvider>
    </LocaleProvider>
  );
};

// packages/vue/src/PioneerContent.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onBeforeUnmount, toRef, provide } from 'vue';
import { X, Download } from 'lucide-vue-next';
import {
  normalizeFiles,
  getFileType,
  downloadFileWithFetcher,
  resolveShowClose,
  type PreviewFile,
  type PreviewFileInput,
  type Locale,
  type Messages,
  type Theme,
  type CustomRendererEventPayload,
  type RequestHandler,
  type RequestInitFactory,
  type ShouldFetchAsBlob,
  type WatermarkConfig,
} from '@pioneer/core';
import type { CustomRenderer, CustomRendererContext } from './types';
import { provideLocale, useTranslator } from './composables/useTranslator';
import { provideResolvedTheme } from './composables/useResolvedTheme';
import { provideRequestContext, useResolvedUrl, useFetcher } from './composables/useRequest';
import type { ToolbarGroup, ToolbarButtonItem, ToolbarTextItem } from './renderers/toolbar.types';
import type { RendererHandle } from './renderers/base.types';
import type { SearchOptions, SearchResult } from '@pioneer/core';
import { BUILTIN_RENDERERS } from './renderers/registry';
// Unsupported 体量极小且每次回退都用，直接静态打包到主入口
import UnsupportedRenderer from './renderers/Unsupported/index.vue';
import NavArrows from './components/NavArrows.vue';
import WatermarkOverlay from './components/WatermarkOverlay.vue';
import SearchPanel from './components/SearchPanel.vue';

const MAX_ZIP_NESTING_DEPTH = 3;

interface Props {
  files: PreviewFileInput[];
  currentIndex: number;
  customRenderers?: CustomRenderer[];
  /** 运行模式: modal(弹窗) 或 embed(嵌入) */
  mode?: 'modal' | 'embed';
  /** ZIP 嵌套深度（内部使用），超过上限时不再递归渲染 ZIP */
  zipNestingDepth?: number;
  /** 语言 */
  locale?: Locale;
  /** 自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  /** 无头模式：隐藏工具栏和导航箭头，仅渲染文件内容 */
  headless?: boolean;
  /** 主题模式，默认 'dark' */
  theme?: Theme;
  /** 自定义 RequestInit（或工厂函数）：注入 Authorization 等鉴权头 */
  requestInit?: RequestInitFactory;
  /** 自定义请求处理器：完全接管库内 fetch */
  requestHandler?: RequestHandler;
  /** 返回 true 时，对应文件先 fetcher→blob URL 后喂给 image/video/audio/pdf 等 renderer */
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  /** 自定义下载回调；不传时库内默认通过 fetcher 拉 Blob 触发下载 */
  onDownload?: (file: PreviewFile) => void | Promise<void>;
  /** 关闭回调 */
  onClose?: () => void;
  /** 是否显示关闭按钮，默认根据 mode 决定（modal: true, embed: false） */
  showClose?: boolean;
  /** 是否显示下载按钮，默认 true */
  showDownload?: boolean;
  /** 水印配置 */
  watermark?: WatermarkConfig;
  /** 加密文件密码 */
  password?: string;
}

const props = withDefaults(defineProps<Props>(), {
  customRenderers: () => [],
  mode: 'modal',
  zipNestingDepth: 0,
  locale: undefined,
  messages: undefined,
  headless: false,
  theme: 'dark',
  requestInit: undefined,
  requestHandler: undefined,
  shouldFetchAsBlob: undefined,
  onDownload: undefined,
  onClose: undefined,
  showClose: undefined,
  showDownload: true,
});

provideRequestContext(() => ({
  requestInit: props.requestInit,
  requestHandler: props.requestHandler,
  shouldFetchAsBlob: props.shouldFetchAsBlob,
}));

const emit = defineEmits<{
  (e: 'navigate', index: number): void;
  (e: 'close'): void;
  (e: 'custom-event', payload: CustomRendererEventPayload): void;
}>();

provideLocale(toRef(props, 'locale'), toRef(props, 'messages'));
const { t } = useTranslator();

const systemDark = ref(
  typeof window !== 'undefined'
    ? window.matchMedia('(prefers-color-scheme: dark)').matches
    : true,
);

let mediaQueryCleanup: (() => void) | null = null;

watch(
  () => props.theme,
  (theme) => {
    if (mediaQueryCleanup) {
      mediaQueryCleanup();
      mediaQueryCleanup = null;
    }
    if (theme === 'auto') {
      const mql = window.matchMedia('(prefers-color-scheme: dark)');
      const handler = (e: MediaQueryListEvent) => { systemDark.value = e.matches; };
      mql.addEventListener('change', handler);
      mediaQueryCleanup = () => mql.removeEventListener('change', handler);
    }
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  if (mediaQueryCleanup) mediaQueryCleanup();
});

const resolvedTheme = computed(() =>
  props.theme === 'auto' ? (systemDark.value ? 'dark' : 'light') : props.theme,
);
provideResolvedTheme(resolvedTheme);

const contentRef = ref<HTMLDivElement | null>(null);
const rootRef = ref<HTMLDivElement | null>(null);

// 渲染器 ref 和工具栏事件订阅
const rendererRef = ref<RendererHandle | null>(null);
const rendererToolbarGroups = ref<ToolbarGroup[]>([]);
let unsubscribeToolbar: (() => void) | null = null;

const cleanupSubscription = () => {
  if (unsubscribeToolbar) {
    unsubscribeToolbar();
    unsubscribeToolbar = null;
  }
};

// 当渲染器变化时，重新订阅工具栏事件
watch(rendererRef, (newRenderer) => {
  cleanupSubscription();
  rendererToolbarGroups.value = [];

  if (!newRenderer) return;

  // 如果渲染器支持事件机制，订阅事件
  if (newRenderer.onToolbarChange) {
    unsubscribeToolbar = newRenderer.onToolbarChange(() => {
      rendererToolbarGroups.value = newRenderer.getToolbarGroups?.() ?? [];
    });
  }

  // 立即获取一次初始工具栏配置
  rendererToolbarGroups.value = newRenderer.getToolbarGroups?.() ?? [];
});

onBeforeUnmount(() => {
  cleanupSubscription();
});

// 标准化文件输入
const normalizedFiles = computed(() => normalizeFiles(props.files));

const currentFile = computed(() => normalizedFiles.value[props.currentIndex]);

// 命中 shouldFetchAsBlob 时，把 file.url 转成 blob: URL 喂给 src 类 renderer
const resolvedUrl = useResolvedUrl(currentFile);

// 自定义渲染器匹配
const customRenderer = computed(() => {
  if (!currentFile.value) return null;
  return props.customRenderers.find((r) => r.test(currentFile.value!)) || null;
});

const customRendererComponent = computed(() => {
  if (!customRenderer.value || !currentFile.value) return null;
  return customRenderer.value.render(currentFile.value, customCtx.value);
});

const fileType = computed(() => (currentFile.value ? getFileType(currentFile.value) : 'unsupported'));

// 从注册表中查找匹配当前 fileType 的内置渲染器
const builtinRenderer = computed(() =>
  BUILTIN_RENDERERS.find((r) => r.fileType === fileType.value) ?? null,
);

// 计算传给内置渲染器的 props
const builtinRendererProps = computed(() => {
  if (!builtinRenderer.value || !currentFile.value) return {};
  return builtinRenderer.value.getProps({
    resolvedUrl: resolvedUrl.value,
    zipNestingDepth: props.zipNestingDepth,
    currentFile: currentFile.value,
    password: props.password,
  });
});

// 自定义渲染器事件派发器：未绑定 @custom-event 时仍调用 emit（Vue 会安全忽略未声明监听）
const emitCustom = (name: string, payload?: unknown) => {
  if (!currentFile.value) return;
  const ev: CustomRendererEventPayload = { name, payload, file: currentFile.value };
  emit('custom-event', ev);
};

// 自定义渲染器上下文
const customCtx = computed<CustomRendererContext>(() => ({
  emit: emitCustom,
  t: t.value,
  theme: resolvedTheme.value,
  locale: (props.locale ?? 'zh-CN') as Locale,
}));

// 通过 provide 暴露给深层子组件 inject 使用
provide('pioneer:custom-ctx', customCtx);

// 重置状态当文件改变时
watch(
  () => props.currentIndex,
  () => {
    // 重置 epub 状态
    epubCurrent.value = 0;
    epubTotal.value = 0;
    epubFullWidth.value = false;
    // 重置 mobi 状态
    mobiCurrent.value = 0;
    mobiTotal.value = 0;
    mobiFullWidth.value = false;
  }
);

// 图片加载后默认适应窗口（已禁用，改为手动点击"适应窗口"按钮）

// 键盘导航
const handleKeyDown = (e: KeyboardEvent) => {
  // Ctrl+F / Cmd+F → 唤起搜索面板
  if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'f') {
    e.preventDefault();
    handleSearchOpen();
    return;
  }
  if (e.key === 'Escape' && props.mode === 'modal') {
    if (searchOpen.value) {
      handleSearchClose();
    } else {
      emit('close');
    }
  } else if (e.key === 'ArrowLeft' && props.currentIndex > 0 && !searchOpen.value) {
    emit('navigate', props.currentIndex - 1);
  } else if (e.key === 'ArrowRight' && props.currentIndex < normalizedFiles.value.length - 1 && !searchOpen.value) {
    emit('navigate', props.currentIndex + 1);
  } else if (e.key === 'ArrowUp' && searchOpen.value) {
    e.preventDefault();
    handleSearchPrev();
  } else if (e.key === 'ArrowDown' && searchOpen.value) {
    e.preventDefault();
    handleSearchNext();
  }
};

onMounted(() => {
  if (props.mode === 'modal') {
    window.addEventListener('keydown', handleKeyDown);
  } else if (rootRef.value) {
    rootRef.value.addEventListener('keydown', handleKeyDown as EventListener);
  }
});

onBeforeUnmount(() => {
  if (props.mode === 'modal') {
    window.removeEventListener('keydown', handleKeyDown);
  } else if (rootRef.value) {
    rootRef.value.removeEventListener('keydown', handleKeyDown as EventListener);
  }
});


const fetcher = useFetcher();
const handleDownload = async () => {
  if (!currentFile.value) return;
  if (props.onDownload) {
    await props.onDownload(currentFile.value);
    return;
  }
  try {
    await downloadFileWithFetcher(currentFile.value.url, currentFile.value.name, fetcher.value);
  } catch (err) {
    console.error('[pioneer] download failed:', err);
  }
};

const showCloseButton = computed(() =>
  resolveShowClose(props.mode, props.showClose),
);

const epubCurrent = ref(0);
const epubTotal = ref(0);
const epubFullWidth = ref(false);

const mobiCurrent = ref(0);
const mobiTotal = ref(0);
const mobiFullWidth = ref(false);

// 防止 ESLint 报未使用警告（仍由模板中的事件回调使用）
void epubCurrent; void epubTotal; void epubFullWidth;
void mobiCurrent; void mobiTotal; void mobiFullWidth;

// ─── 搜索状态 ───
const searchOpen = ref(false);
const searchResults = ref<SearchResult>({ total: 0, current: -1, matches: [] });
const searchQuery = ref('');
const searchCaseSensitive = ref(false);

const canSearch = computed(() => {
  const renderer = rendererRef.value;
  return renderer?.canSearch?.() ?? false;
});

async function handleSearch(query: string, options: SearchOptions) {
  const renderer = rendererRef.value;
  if (!renderer || !renderer.search || !query.trim()) {
    searchResults.value = { total: 0, current: -1, matches: [] };
    return;
  }
  try {
    searchResults.value = await renderer.search(query, { ...options, caseSensitive: options.caseSensitive ?? false });
  } catch {
    searchResults.value = { total: 0, current: -1, matches: [] };
  }
}

function handleSearchPrev() {
  rendererRef.value?.goToPrevMatch?.();
}

function handleSearchNext() {
  rendererRef.value?.goToNextMatch?.();
}

function handleSearchClose() {
  searchOpen.value = false;
  rendererRef.value?.clearSearch?.();
  searchResults.value = { total: 0, current: -1, matches: [] };
  searchQuery.value = '';
}

function handleSearchOpen() {
  if (!canSearch.value) return;
  searchOpen.value = true;
}

// 工具栏配置 — 各 Renderer 自行通过 ref 暴露 getToolbarGroups 和 onToolbarChange
const toolGroups = computed(() => {
  if (customRenderer.value) {
    return (
      customRenderer.value.getToolbarGroups?.(currentFile.value!, customCtx.value) ?? []
    );
  }
  // 所有内置渲染器都通过事件驱动机制提供工具栏
  return rendererToolbarGroups.value;
});

// 操作组：下载、关闭（通用，不属于任何 Renderer）
const actionGroups = computed<ToolbarGroup[]>(() => {
  const groups: ToolbarGroup[] = [];
  if (props.showDownload) {
    groups.push({
      items: [
        { type: 'button', icon: Download, tooltip: t.value('common.download'), action: handleDownload },
      ],
    });
  }
  if (showCloseButton.value) {
    groups.push({
      items: [
        { type: 'button', icon: X, tooltip: t.value('common.close'), action: () => emit('close') },
      ],
    });
  }
  return groups;
});

const hasToolGroups = computed(() => toolGroups.value.length > 0);
</script>

<template>
  <div
    ref="rootRef"
    :tabindex="mode === 'embed' ? 0 : -1"
    :data-theme="resolvedTheme"
    class="pio-relative pio-w-full pio-h-full pio-flex pio-flex-col pio-overflow-hidden pio-outline-none"
  >
    <!-- 顶部工具栏 -->
    <div
      v-if="!headless"
      class="pio-flex-shrink-0 pio-z-10 pio-backdrop-blur-md pio-border-b pio-bg-surface-toolbar pio-border-line"
      style="padding-top: env(safe-area-inset-top, 0px)"
    >
      <!-- 第一行: 文件名 + 桌面端工具按钮 -->
      <div class="pio-flex pio-items-center pio-justify-between pio-px-3 md:pio-px-5 pio-py-1.5 md:pio-py-2.5">
        <!-- 左侧: 文件名 + 分页 -->
        <div class="pio-flex pio-items-center pio-flex-1 pio-min-w-0 pio-mr-2 md:pio-mr-3">
          <h2 class="pio-font-medium pio-text-xs md:pio-text-sm pio-truncate pio-text-fg-primary">
            {{ currentFile?.name }}
          </h2>
          <span class="pio-text-xs pio-ml-2 pio-flex-shrink-0 pio-text-fg-muted">
            {{ currentIndex + 1 }}/{{ normalizedFiles.length }}
          </span>
        </div>

        <!-- 移动端: 仅下载 + 关闭 -->
        <div class="pio-flex pio-items-center pio-gap-1 md:pio-hidden pio-flex-shrink-0">
          <template v-for="(group, gi) in actionGroups" :key="'m-action-' + gi">
            <template v-for="(item, ii) in group.items" :key="'m-action-' + gi + '-' + ii">
              <button
                v-if="item.type === 'button'"
                class="toolbar-btn"
                :class="{ active: (item as ToolbarButtonItem).active }"
                :data-tooltip="(item as ToolbarButtonItem).tooltip"
                :disabled="(item as ToolbarButtonItem).disabled"
                :aria-pressed="(item as ToolbarButtonItem).active"
                @click="(item as ToolbarButtonItem).action"
              >
                <component :is="(item as ToolbarButtonItem).icon" class="pio-w-4 pio-h-4" />
              </button>
            </template>
          </template>
        </div>

        <!-- 桌面端: 完整工具按钮 -->
        <div class="pio-hidden md:pio-flex pio-items-center pio-gap-1 pio-flex-shrink-0">
          <template v-for="(group, gi) in toolGroups" :key="'d-tool-' + gi">
            <template v-for="(item, ii) in group.items" :key="'d-tool-' + gi + '-' + ii">
              <button
                v-if="item.type === 'button'"
                class="toolbar-btn"
                :class="{ active: (item as ToolbarButtonItem).active }"
                :data-tooltip="(item as ToolbarButtonItem).tooltip"
                :disabled="(item as ToolbarButtonItem).disabled"
                :aria-pressed="(item as ToolbarButtonItem).active"
                @click="(item as ToolbarButtonItem).action"
              >
                <component :is="(item as ToolbarButtonItem).icon" class="pio-w-4 pio-h-4" />
              </button>
              <span
                v-else-if="item.type === 'text'"
                class="pio-text-xs pio-text-center pio-font-medium pio-tabular-nums pio-text-fg-tertiary"
                :style="{ minWidth: (item as ToolbarTextItem).minWidth || 'auto' }"
              >
                {{ (item as ToolbarTextItem).content }}
              </span>
            </template>
            <div v-if="gi < toolGroups.length - 1 || actionGroups.length > 0" class="pio-w-px pio-h-4 pio-mx-1 pio-bg-divide" />
          </template>
          <template v-for="(group, gi) in actionGroups" :key="'d-action-' + gi">
            <template v-for="(item, ii) in group.items" :key="'d-action-' + gi + '-' + ii">
              <button
                v-if="item.type === 'button'"
                class="toolbar-btn"
                :class="{ active: (item as ToolbarButtonItem).active }"
                :data-tooltip="(item as ToolbarButtonItem).tooltip"
                :disabled="(item as ToolbarButtonItem).disabled"
                :aria-pressed="(item as ToolbarButtonItem).active"
                @click="(item as ToolbarButtonItem).action"
              >
                <component :is="(item as ToolbarButtonItem).icon" class="pio-w-4 pio-h-4" />
              </button>
            </template>
          </template>
        </div>
      </div>

      <!-- 移动端第二行工具按钮 -->
      <div
        v-if="hasToolGroups"
        class="pio-flex pio-items-center pio-gap-1 pio-px-3 pio-pb-1.5 pio-overflow-x-auto scrollbar-hide md:pio-hidden"
      >
        <template v-for="(group, gi) in toolGroups" :key="'m-tool-' + gi">
          <div v-if="gi > 0" class="pio-w-px pio-h-4 pio-mx-0.5 pio-bg-divide" />
          <template v-for="(item, ii) in group.items" :key="'m-tool-' + gi + '-' + ii">
            <button
              v-if="item.type === 'button'"
              class="toolbar-btn"
              :class="{ active: (item as ToolbarButtonItem).active }"
              :data-tooltip="(item as ToolbarButtonItem).tooltip"
              :disabled="(item as ToolbarButtonItem).disabled"
              :aria-pressed="(item as ToolbarButtonItem).active"
              @click="(item as ToolbarButtonItem).action"
            >
              <component :is="(item as ToolbarButtonItem).icon" class="pio-w-4 pio-h-4" />
            </button>
            <span
              v-else-if="item.type === 'text'"
              class="pio-text-xs pio-text-center pio-font-medium pio-tabular-nums pio-text-fg-tertiary"
              :style="{ minWidth: (item as ToolbarTextItem).minWidth || 'auto' }"
            >
              {{ (item as ToolbarTextItem).content }}
            </span>
          </template>
        </template>
      </div>
    </div>

    <!-- 搜索面板：搜索激活时显示在工具栏下方 -->
    <SearchPanel
      v-if="!headless && searchOpen && canSearch"
      :on-close="handleSearchClose"
      :on-search="(q, o) => { searchQuery = q; searchCaseSensitive = o.caseSensitive; handleSearch(q, o); }"
      :on-prev-match="handleSearchPrev"
      :on-next-match="handleSearchNext"
      :match-count="searchResults.current"
      :total-count="searchResults.total"
    />

    <!-- 内容区域 -->
    <div
      ref="contentRef"
      class="pio-relative pio-flex-1 pio-flex pio-items-center pio-justify-center pio-overflow-hidden"
      :key="currentFile?.url"
    >
      <template v-if="currentFile">
        <component :is="customRendererComponent" v-if="customRendererComponent" :file="currentFile" :ctx="customCtx" />
        <template v-else>
          <!-- ZIP 嵌套深度超限：fallback 到 Unsupported -->
          <UnsupportedRenderer
            v-if="fileType === 'zip' && props.zipNestingDepth >= MAX_ZIP_NESTING_DEPTH"
            :file-name="currentFile.name"
            :file-type="currentFile.type"
            @download="handleDownload"
          />
          <!-- 从注册表查找匹配的渲染器 -->
          <component
            v-else-if="builtinRenderer"
            :is="builtinRenderer.component"
            ref="rendererRef"
            v-bind="builtinRendererProps"
          />
          <!-- 未匹配：fallback 到 UnsupportedRenderer -->
          <UnsupportedRenderer
            v-else
            :file-name="currentFile.name"
            :file-type="currentFile.type"
            @download="handleDownload"
          />
        </template>
      </template>

      <!-- 水印层：位于渲染器内容之上，pointer-events: none 不干扰交互 -->
      <WatermarkOverlay
        v-if="!headless && watermark"
        :config="watermark"
        :theme="resolvedTheme"
        :container-ref="contentRef"
      />
    </div>

    <!-- 左右导航箭头：state 隔离在 NavArrows 内部,避免 mousemove/timer 引起整树 patch -->
    <NavArrows
      v-if="!headless && normalizedFiles.length > 1"
      :container-ref="contentRef"
      :has-prev="currentIndex > 0"
      :has-next="currentIndex < normalizedFiles.length - 1"
      :reset-key="currentIndex"
      @prev="emit('navigate', currentIndex - 1)"
      @next="emit('navigate', currentIndex + 1)"
    />
  </div>
</template>

<style scoped>
.toolbar-btn {
  position: relative;
  padding: 0.5rem;
  border-radius: 0.375rem;
  transition: all 0.15s;
  user-select: none;
  color: var(--pio-fg-primary);
  background: transparent;
  border: 0;
  cursor: pointer;
}
@media (min-width: 768px) {
  .toolbar-btn {
    padding: 0.375rem;
  }
}
.toolbar-btn:hover {
  background: var(--pio-surface-2);
}
.toolbar-btn:active {
  background: var(--pio-surface-3);
}
.toolbar-btn.active,
.toolbar-btn.active:hover,
.toolbar-btn.active:active {
  background: var(--pio-surface-3);
}
.toolbar-btn:disabled {
  color: var(--pio-fg-disabled);
  cursor: not-allowed;
}
/* Tooltip */
.toolbar-btn[data-tooltip]::after {
  content: attr(data-tooltip);
  position: absolute;
  left: 50%;
  top: 100%;
  transform: translateX(-50%);
  margin-top: 6px;
  padding: 4px 8px;
  background: var(--pio-fg-primary);
  color: var(--pio-fg-inverse);
  font-size: 12px;
  line-height: 1.5;
  border-radius: 4px;
  white-space: nowrap;
  pointer-events: none;
  opacity: 0;
  visibility: hidden;
  transition: opacity 0.2s, visibility 0.2s;
  z-index: 50;
}
.toolbar-btn[data-tooltip]::before {
  content: '';
  position: absolute;
  left: 50%;
  top: 100%;
  transform: translateX(-50%);
  margin-top: 2px;
  border: 4px solid transparent;
  border-bottom-color: var(--pio-fg-primary);
  pointer-events: none;
  opacity: 0;
  visibility: hidden;
  transition: opacity 0.2s, visibility 0.2s;
  z-index: 50;
}
.toolbar-btn[data-tooltip]:hover::after,
.toolbar-btn[data-tooltip]:hover::before {
  opacity: 1;
  visibility: visible;
}

/* 移动端隐藏 tooltip */
@media (max-width: 1023px) {
  .toolbar-btn[data-tooltip]::after,
  .toolbar-btn[data-tooltip]::before {
    display: none !important;
  }
}
</style>
