// packages/react/src/renderers/Subtitle/index.tsx
import { useState, useEffect, useMemo, forwardRef, useImperativeHandle } from 'react';
import {
  parseSubtitle,
  formatSubtitleTime,
  fetchTextUtf8,
  type SubtitleParseResult,
  type SubtitleFormat,
} from '@pioneer/core';
import { useTranslator } from '../../i18n/LocaleContext';
import { useFetcher } from '../../RequestContext';
import { RendererError } from '../RendererError';
import type { RendererHandle } from '../base.types';

interface SubtitleRendererProps {
  url: string;
  fileName: string;
}

const FORMAT_BY_EXT: Record<string, SubtitleFormat> = {
  srt: 'srt',
  vtt: 'vtt',
  lrc: 'lrc',
  elrc: 'elrc',
  ass: 'ass',
  ssa: 'ssa',
  ttml: 'ttml',
  dfxp: 'ttml',
};

const getFormat = (fileName: string): SubtitleFormat | undefined => {
  const ext = fileName.split('.').pop()?.toLowerCase() || '';
  return FORMAT_BY_EXT[ext];
};

export const SubtitleRenderer = forwardRef<RendererHandle, SubtitleRendererProps>(({ url, fileName }, ref) => {
  const t = useTranslator();
  const fetcher = useFetcher();
  const [text, setText] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const controller = new AbortController();
    const load = async () => {
      try {
        setLoading(true);
        setError(null);
        setText(await fetchTextUtf8(url, { fetcher, signal: controller.signal }));
      } catch (err: any) {
        if (err.name === 'AbortError') return;
        console.warn('[SubtitleRenderer] Failed to load subtitle:', err instanceof Error ? err.message : String(err));
        setError(t('subtitle.load_failed'));
      } finally {
        setLoading(false);
      }
    };
    load();
    return () => controller.abort();
  }, [url]);

  const parsed: SubtitleParseResult | null = useMemo(() => {
    if (!text) return null;
    try {
      return parseSubtitle(text, getFormat(fileName));
    } catch (err) {
      // 字幕解析失败通常是格式不支持或文件损坏，用 warn 级别记录
      console.warn('[SubtitleRenderer] Failed to parse subtitle:', err instanceof Error ? err.message : String(err));
      return null;
    }
  }, [text, fileName]);

  // 暴露接口给父组件
  useImperativeHandle(ref, () => ({
    getToolbarGroups: () => [],
  }), []);

  if (loading) {
    return (
      <div className="pio-flex pio-items-center pio-justify-center pio-w-full pio-h-full pio-bg-[#0f0f12]">
        <div className="pio-w-12 pio-h-12 pio-border-4 pio-border-line-strong pio-border-t-spinner-head pio-rounded-full pio-animate-spin" />
      </div>
    );
  }

  if (error || !parsed) {
    return <RendererError message={error || t('subtitle.parse_failed')} />;
  }

  const isLyric = parsed.format === 'lrc' || parsed.format === 'elrc';
  const meta = parsed.metadata ?? {};
  const dotHover = isLyric ? 'group-hover:pio-bg-violet-400' : 'group-hover:pio-bg-sky-400';

  return (
    <div className="pio-relative pio-w-full pio-h-full pio-bg-[#0f0f12]">
      {/* 内容滚动区 */}
      <div className="pio-w-full pio-h-full pio-overflow-auto pio-px-4 pio-pt-6 pio-pb-16">
        <div className="pio-relative">
          {/* vertical line */}
          <div className="pio-absolute pio-left-[5px] pio-top-2 pio-bottom-2 pio-w-px pio-bg-surface-1" />

          <ol className="pio-space-y-5">
            {parsed.cues.map((cue, i) => (
              <li key={`cue-${i}`} className="pio-relative pio-pl-6 pio-group">
                {/* dot */}
                <div
                  className={`pio-absolute pio-left-0 pio-top-[0.4rem] pio-w-3 pio-h-3 pio-rounded-full pio-bg-surface-3 pio-border-2 pio-border-[#0f0f12] pio-transition-colors ${dotHover}`}
                />

                <div className="pio-flex pio-flex-wrap pio-items-baseline pio-gap-x-3 pio-gap-y-1 pio-mb-1.5">
                  <span className="pio-text-[11px] pio-font-mono pio-text-fg-muted pio-tabular-nums">
                    {formatSubtitleTime(cue.start)}
                  </span>
                  <span className="pio-text-[11px] pio-text-fg-disabled">→</span>
                  <span className="pio-text-[11px] pio-font-mono pio-text-fg-muted pio-tabular-nums">
                    {formatSubtitleTime(cue.end)}
                  </span>
                  <span className="pio-text-[10px] pio-font-mono pio-text-fg-disabled pio-tabular-nums">
                    #{cue.id ?? i + 1}
                  </span>
                  {cue.style && (
                    <span className="pio-text-[9px] pio-uppercase pio-tracking-widest pio-text-fg-tertiary pio-px-1.5 pio-py-0.5 pio-rounded pio-bg-surface-1 pio-border pio-border-line-weak">
                      {cue.style}
                    </span>
                  )}
                </div>

                {cue.words && cue.words.length > 0 ? (
                  <div className="pio-flex pio-flex-wrap pio-gap-x-1.5 pio-gap-y-1 pio-text-base pio-text-fg-primary pio-leading-relaxed group-hover:pio-text-fg-primary pio-transition-colors">
                    {cue.words.map((word, wi) => (
                      <span
                        key={`w-${wi}`}
                        className="pio-inline-flex pio-flex-col pio-items-start"
                        title={formatSubtitleTime(word.start)}
                      >
                        <span className="pio-text-[9px] pio-text-fg-disabled pio-font-mono pio-leading-none pio-tabular-nums">
                          {formatSubtitleTime(word.start).slice(3, 8)}
                        </span>
                        <span className="pio-leading-snug">{word.text}</span>
                      </span>
                    ))}
                  </div>
                ) : (
                  <p
                    className={`pio-whitespace-pre-wrap pio-break-words pio-leading-relaxed group-hover:pio-text-fg-primary pio-transition-colors pio-text-fg-primary pio-min-h-[1.25rem] ${
                      isLyric ? 'pio-text-base pio-font-medium' : 'pio-text-sm'
                    }`}
                  >
                    {cue.text}
                  </p>
                )}
              </li>
            ))}
          </ol>
        </div>
      </div>

      {/* 底部状态栏 */}
      <div className="pio-pointer-events-none pio-absolute pio-bottom-3 pio-right-3 pio-flex pio-items-center pio-gap-2 pio-px-2.5 pio-py-1 pio-rounded-full pio-bg-surface-nav pio-backdrop-blur pio-border pio-border-line-weak pio-text-[10px] pio-text-fg-tertiary pio-font-mono pio-tabular-nums">
        <span>{parsed.cues.length} {isLyric ? t('subtitle.lines') : t('subtitle.cues')}</span>
        {meta.length && (
          <>
            <span className="pio-text-fg-disabled">·</span>
            <span>{meta.length}</span>
          </>
        )}
      </div>
    </div>
  );
});

// packages/vue/src/renderers/Subtitle/index.vue
<script setup lang="ts">
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';

import { ref, computed, watch } from 'vue';
import {
  parseSubtitle,
  formatSubtitleTime,
  fetchTextUtf8,
  type SubtitleParseResult,
  type SubtitleFormat,
} from '@pioneer/core';
import { useTranslator } from '../../composables/useTranslator';
import { useFetcher } from '../../composables/useRequest';
import RendererError from '../RendererError.vue';

const props = defineProps<{
  url: string;
  fileName: string;
}>();

const { t } = useTranslator();
const fetcher = useFetcher();

const text = ref<string>('');
const loading = ref(true);
const error = ref<string | null>(null);

const FORMAT_BY_EXT: Record<string, SubtitleFormat> = {
  srt: 'srt',
  vtt: 'vtt',
  lrc: 'lrc',
  elrc: 'elrc',
  ass: 'ass',
  ssa: 'ssa',
  ttml: 'ttml',
  dfxp: 'ttml',
};

const getFormat = (fileName: string): SubtitleFormat | undefined => {
  const ext = fileName.split('.').pop()?.toLowerCase() || '';
  return FORMAT_BY_EXT[ext];
};

const load = async () => {
  loading.value = true;
  error.value = null;
  try {
    text.value = await fetchTextUtf8(props.url, { fetcher: fetcher.value });
  } catch (err) {
    console.error(err);
    error.value = t.value('subtitle.load_failed');
  } finally {
    loading.value = false;
  }
};

watch(() => props.url, load, { immediate: true });

const parsed = computed<SubtitleParseResult | null>(() => {
  if (!text.value) return null;
  try {
    return parseSubtitle(text.value, getFormat(props.fileName));
  } catch (err) {
    console.error(err);
    return null;
  }
});

const isLyric = computed(() => parsed.value?.format === 'lrc' || parsed.value?.format === 'elrc');

const meta = computed<Record<string, string>>(() => parsed.value?.metadata ?? {});

const wordTimeShort = (t: number) => formatSubtitleTime(t).slice(3, 8);

const getToolbarGroups = (): ToolbarGroup[] => [];

defineExpose<RendererHandle>({
  getToolbarGroups,
});

</script>

<template>
  <div
    v-if="loading"
    class="pio-flex pio-items-center pio-justify-center pio-w-full pio-h-full pio-bg-[#0f0f12]"
  >
    <div
      class="pio-w-12 pio-h-12 pio-border-4 pio-border-line-strong pio-border-t-spinner-head pio-rounded-full pio-animate-spin"
    />
  </div>

  <RendererError
    v-else-if="error || !parsed"
    :message="error || t('subtitle.parse_failed')"
    class="pio-bg-[#0f0f12]"
  />

  <div
    v-else
    class="pio-relative pio-w-full pio-h-full pio-bg-[#0f0f12]"
    :class="isLyric ? 'flavor-lyric' : 'flavor-subtitle'"
  >
    <!-- 内容滚动区 -->
    <div class="content-scroll">
      <div class="timeline">
        <div class="timeline-line" />
        <ol class="cues">
          <li v-for="(cue, i) in parsed.cues" :key="'cue-' + i" class="cue-row">
            <div class="cue-dot" />
            <div class="cue-meta">
              <span class="cue-time">{{ formatSubtitleTime(cue.start) }}</span>
              <span class="cue-arrow">→</span>
              <span class="cue-time">{{ formatSubtitleTime(cue.end) }}</span>
              <span class="cue-id">#{{ cue.id ?? i + 1 }}</span>
              <span v-if="cue.style" class="cue-style">{{ cue.style }}</span>
            </div>
            <div v-if="cue.words && cue.words.length > 0" class="cue-words">
              <span
                v-for="(word, wi) in cue.words"
                :key="'w-' + wi"
                class="cue-word"
                :title="formatSubtitleTime(word.start)"
              >
                <span class="cue-word-time">{{ wordTimeShort(word.start) }}</span>
                <span class="cue-word-text">{{ word.text }}</span>
              </span>
            </div>
            <p v-else class="cue-text" :class="{ lyric: isLyric }">{{ cue.text }}</p>
          </li>
        </ol>
      </div>
    </div>

    <!-- 右下角浮签 -->
    <div class="status-pill">
      <span>{{ parsed.cues.length }} {{ isLyric ? t('subtitle.lines') : t('subtitle.cues') }}</span>
      <template v-if="meta.length">
        <span class="dot">·</span>
        <span>{{ meta.length }}</span>
      </template>
    </div>
  </div>
</template>

<style scoped>
.content-scroll {
  width: 100%;
  height: 100%;
  overflow: auto;
  padding: 1.5rem 1rem 4rem;
}
.status-pill {
  pointer-events: none;
  position: absolute;
  bottom: 0.75rem;
  right: 0.75rem;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.25rem 0.625rem;
  border-radius: 9999px;
  background: rgba(0, 0, 0, 0.4);
  backdrop-filter: blur(8px);
  border: 1px solid var(--pio-line);
  font-size: 0.625rem;
  color: var(--pio-fg-tertiary);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-variant-numeric: tabular-nums;
}
.dot {
  color: var(--pio-fg-disabled);
}

.timeline {
  position: relative;
}
.timeline-line {
  position: absolute;
  left: 5px;
  top: 0.5rem;
  bottom: 0.5rem;
  width: 1px;
  background: var(--pio-line-weak);
}
.cues {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}
.cue-row {
  position: relative;
  padding-left: 1.5rem;
}
.cue-dot {
  position: absolute;
  left: 0;
  top: 0.4rem;
  width: 0.75rem;
  height: 0.75rem;
  border-radius: 9999px;
  background: var(--pio-surface-3);
  border: 2px solid #0f0f12;
  transition: background-color 0.2s;
}
.flavor-lyric .cue-row:hover .cue-dot {
  background: rgb(167, 139, 250);
}
.flavor-subtitle .cue-row:hover .cue-dot {
  background: rgb(56, 189, 248);
}
.cue-meta {
  display: flex;
  flex-wrap: wrap;
  align-items: baseline;
  gap: 0.25rem 0.75rem;
  margin-bottom: 0.375rem;
}
.cue-time {
  font-size: 0.6875rem;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  color: var(--pio-fg-muted);
  font-variant-numeric: tabular-nums;
}
.cue-arrow {
  font-size: 0.6875rem;
  color: var(--pio-fg-disabled);
}
.cue-id {
  font-size: 0.625rem;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  color: var(--pio-fg-disabled);
  font-variant-numeric: tabular-nums;
}
.cue-style {
  font-size: 0.5625rem;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--pio-fg-tertiary);
  padding: 0.125rem 0.375rem;
  border-radius: 0.25rem;
  background: var(--pio-line-weak);
  border: 1px solid var(--pio-line);
}
.cue-text {
  margin: 0;
  white-space: pre-wrap;
  word-break: break-word;
  line-height: 1.625;
  color: var(--pio-fg-primary);
  font-size: 0.875rem;
  min-height: 1.25rem;
  transition: color 0.2s;
}
.cue-text.lyric {
  font-size: 1rem;
  font-weight: 500;
}
.cue-row:hover .cue-text {
  color: #fff;
}
.cue-words {
  display: flex;
  flex-wrap: wrap;
  gap: 0.25rem 0.375rem;
  font-size: 1rem;
  color: var(--pio-fg-primary);
  line-height: 1.625;
  transition: color 0.2s;
}
.cue-row:hover .cue-words {
  color: #fff;
}
.cue-word {
  display: inline-flex;
  flex-direction: column;
  align-items: flex-start;
}
.cue-word-time {
  font-size: 0.5625rem;
  color: var(--pio-fg-disabled);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  line-height: 1;
  font-variant-numeric: tabular-nums;
}
.cue-word-text {
  line-height: 1.4;
}
</style>
