// packages/react/src/components/ResizableSplit.tsx
import React, { useEffect, useImperativeHandle, useRef, useState, useCallback, forwardRef } from 'react';

export interface ResizableSplitProps {
  /** 左侧内容 */
  left: React.ReactNode;
  /** 右侧内容 */
  right: React.ReactNode;
  /** 左侧初始宽度（px）；传入 storageKey 时会从 localStorage 读取 */
  initialLeftWidth?: number;
  /** 左侧最小宽度（px） */
  minLeftWidth?: number;
  /** 左侧最大宽度（px），同时不超过 `容器宽 - minRightWidth - 分隔线宽` */
  maxLeftWidth?: number;
  /** 右侧至少保留的宽度（px） */
  minRightWidth?: number;
  /** localStorage 持久化 key；不传则不持久化 */
  storageKey?: string;
  /** 启用横向拖动的媒体查询，默认 `(min-width: 768px)` */
  desktopMedia?: string;
  /** 容器额外类名 */
  className?: string;
  /** 移动端使用 Tab 切换而非上下堆叠 */
  mobileTabMode?: boolean;
  /** Tab 模式下左侧标题 */
  leftTabLabel?: string;
  /** Tab 模式下右侧标题 */
  rightTabLabel?: string;
}

export interface ResizableSplitHandle {
  switchTab: (tab: 'left' | 'right') => void;
}

/**
 * 通用可拖动分隔布局：
 * - 桌面端（由 `desktopMedia` 判定）横向分两栏，中间分隔线可左右拖动调整左栏宽度
 * - 移动端默认退化为上下堆叠（不显示分隔线）
 * - 设置 `mobileTabMode` 时移动端使用 Tab 切换显示
 * - 可选 `storageKey` 将宽度持久化到 localStorage
 */
export const ResizableSplit = forwardRef<ResizableSplitHandle, ResizableSplitProps>(({
  left,
  right,
  initialLeftWidth = 280,
  minLeftWidth = 160,
  maxLeftWidth = 640,
  minRightWidth = 200,
  storageKey,
  desktopMedia = '(min-width: 768px)',
  className = '',
  mobileTabMode = false,
  leftTabLabel = '文件树',
  rightTabLabel = '预览',
}, ref) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [leftWidth, setLeftWidth] = useState<number>(() => {
    if (storageKey && typeof window !== 'undefined') {
      const saved = Number(window.localStorage.getItem(storageKey));
      if (!isNaN(saved) && saved > 0) return saved;
    }
    return initialLeftWidth;
  });
  const [dragging, setDragging] = useState(false);
  const [isDesktop, setIsDesktop] = useState(false);
  const [activeTab, setActiveTab] = useState<'left' | 'right'>('left');

  useImperativeHandle(ref, () => ({
    switchTab: (tab) => setActiveTab(tab),
  }), []);

  // 响应式：监听媒体查询
  useEffect(() => {
    if (typeof window === 'undefined') return;
    const mq = window.matchMedia(desktopMedia);
    const handler = () => setIsDesktop(mq.matches);
    handler();
    mq.addEventListener('change', handler);
    return () => mq.removeEventListener('change', handler);
  }, [desktopMedia]);

  // 拖动
  useEffect(() => {
    if (!dragging) return;
    const handleMove = (e: MouseEvent) => {
      if (!containerRef.current) return;
      const rect = containerRef.current.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const cap = rect.width - minRightWidth - 6;
      const effectiveMax = Math.min(maxLeftWidth, cap);
      const newW = Math.max(minLeftWidth, Math.min(effectiveMax, x));
      setLeftWidth(newW);
    };
    const handleUp = () => setDragging(false);
    window.addEventListener('mousemove', handleMove);
    window.addEventListener('mouseup', handleUp);
    const prevCursor = document.body.style.cursor;
    const prevSelect = document.body.style.userSelect;
    document.body.style.cursor = 'col-resize';
    document.body.style.userSelect = 'none';
    return () => {
      window.removeEventListener('mousemove', handleMove);
      window.removeEventListener('mouseup', handleUp);
      document.body.style.cursor = prevCursor;
      document.body.style.userSelect = prevSelect;
    };
  }, [dragging, minLeftWidth, maxLeftWidth, minRightWidth]);

  // 持久化
  useEffect(() => {
    if (!storageKey || dragging) return;
    try {
      window.localStorage.setItem(storageKey, String(leftWidth));
    } catch {
      // ignore
    }
  }, [leftWidth, storageKey, dragging]);

  const handleDividerDown = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    setDragging(true);
  }, []);

  // 移动端 Tab 模式
  if (mobileTabMode && !isDesktop) {
    return (
      <div
        ref={containerRef}
        className={`pio-w-full pio-h-full pio-flex pio-flex-col pio-min-h-0 pio-min-w-0 ${className}`}
      >
        <div className="pio-flex pio-flex-shrink-0 pio-border-b pio-border-line-weak pio-bg-surface-toolbar">
          <button
            type="button"
            onClick={() => setActiveTab('left')}
            className={`pio-flex-1 pio-py-2.5 pio-text-sm pio-transition-colors ${
              activeTab === 'left'
                ? 'pio-text-fg-primary pio-border-b-2 pio-border-fg-primary -pio-mb-px'
                : 'pio-text-fg-secondary'
            }`}
          >
            {leftTabLabel}
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('right')}
            className={`pio-flex-1 pio-py-2.5 pio-text-sm pio-transition-colors ${
              activeTab === 'right'
                ? 'pio-text-fg-primary pio-border-b-2 pio-border-fg-primary -pio-mb-px'
                : 'pio-text-fg-secondary'
            }`}
          >
            {rightTabLabel}
          </button>
        </div>
        <div
          className="pio-flex-1 pio-min-h-0 pio-min-w-0 pio-w-full pio-overflow-hidden"
          style={{ display: activeTab === 'left' ? undefined : 'none' }}
        >
          {left}
        </div>
        <div
          className="pio-flex-1 pio-min-h-0 pio-min-w-0 pio-w-full pio-overflow-hidden"
          style={{ display: activeTab === 'right' ? undefined : 'none' }}
        >
          {right}
        </div>
      </div>
    );
  }

  return (
    <div
      ref={containerRef}
      className={`pio-w-full pio-h-full pio-flex pio-flex-col md:pio-flex-row pio-min-h-0 pio-min-w-0 ${className}`}
    >
      <div
        className="pio-min-h-0 pio-min-w-0 pio-flex-shrink-0 pio-w-full pio-max-h-60 md:pio-h-full md:pio-max-h-none"
        style={isDesktop ? { width: `${leftWidth}px` } : undefined}
      >
        {left}
      </div>
      {/* 分隔线：仅桌面显示 */}
      <div
        role="separator"
        aria-orientation="vertical"
        onMouseDown={handleDividerDown}
        className={`pio-hidden md:pio-block pio-relative pio-w-1.5 pio-flex-shrink-0 pio-cursor-col-resize pio-transition-colors ${
          dragging ? 'pio-bg-surface-toolbar' : 'pio-bg-surface-2 hover:pio-bg-surface-3'
        }`}
      >
        {/* 加宽命中区，改善拖动体验 */}
        <span className="pio-absolute pio-inset-y-0 -pio-left-1 -pio-right-1" />
      </div>
      <div className="pio-flex-1 pio-min-w-0 pio-min-h-0 pio-overflow-hidden">{right}</div>
    </div>
  );
});

ResizableSplit.displayName = 'ResizableSplit';

// packages/vue/src/components/ResizableSplit.vue
<script setup lang="ts">
import { ref, computed, onBeforeUnmount, onMounted, watch } from 'vue';

interface Props {
  /** 左侧初始宽度（px）；传入 storageKey 时会从 localStorage 读取 */
  initialLeftWidth?: number;
  /** 左侧最小宽度（px） */
  minLeftWidth?: number;
  /** 左侧最大宽度（px） */
  maxLeftWidth?: number;
  /** 右侧至少保留的宽度（px） */
  minRightWidth?: number;
  /** localStorage 持久化 key */
  storageKey?: string;
  /** 启用横向拖动的媒体查询 */
  desktopMedia?: string;
  /** 移动端使用 Tab 切换而非上下堆叠 */
  mobileTabMode?: boolean;
  /** Tab 模式下左侧标题 */
  leftTabLabel?: string;
  /** Tab 模式下右侧标题 */
  rightTabLabel?: string;
}

const props = withDefaults(defineProps<Props>(), {
  initialLeftWidth: 280,
  minLeftWidth: 160,
  maxLeftWidth: 640,
  minRightWidth: 200,
  desktopMedia: '(min-width: 768px)',
  mobileTabMode: false,
  leftTabLabel: '文件树',
  rightTabLabel: '预览',
});

defineOptions({ name: 'ResizableSplit' });

const containerRef = ref<HTMLDivElement | null>(null);
const leftWidth = ref<number>(
  (() => {
    if (props.storageKey && typeof window !== 'undefined') {
      const saved = Number(window.localStorage.getItem(props.storageKey));
      if (!isNaN(saved) && saved > 0) return saved;
    }
    return props.initialLeftWidth;
  })()
);
const dragging = ref(false);
const isDesktop = ref(false);
const activeTab = ref<'left' | 'right'>('left');

let mq: MediaQueryList | null = null;
const mqHandler = () => {
  if (mq) isDesktop.value = mq.matches;
};

const leftStyle = computed(() =>
  isDesktop.value ? { width: `${leftWidth.value}px` } : undefined
);

const onMove = (e: MouseEvent) => {
  if (!containerRef.value) return;
  const rect = containerRef.value.getBoundingClientRect();
  const x = e.clientX - rect.left;
  const cap = rect.width - props.minRightWidth - 6;
  const effectiveMax = Math.min(props.maxLeftWidth, cap);
  leftWidth.value = Math.max(
    props.minLeftWidth,
    Math.min(effectiveMax, x)
  );
};

const onUp = () => {
  if (!dragging.value) return;
  dragging.value = false;
  window.removeEventListener('mousemove', onMove);
  window.removeEventListener('mouseup', onUp);
  document.body.style.cursor = '';
  document.body.style.userSelect = '';
  if (props.storageKey) {
    try {
      window.localStorage.setItem(props.storageKey, String(leftWidth.value));
    } catch {
      // ignore
    }
  }
};

const onDividerDown = (e: MouseEvent) => {
  e.preventDefault();
  dragging.value = true;
  window.addEventListener('mousemove', onMove);
  window.addEventListener('mouseup', onUp);
  document.body.style.cursor = 'col-resize';
  document.body.style.userSelect = 'none';
};

onMounted(() => {
  if (typeof window !== 'undefined') {
    mq = window.matchMedia(props.desktopMedia);
    mqHandler();
    mq.addEventListener('change', mqHandler);
  }
});

onBeforeUnmount(() => {
  if (mq) mq.removeEventListener('change', mqHandler);
  window.removeEventListener('mousemove', onMove);
  window.removeEventListener('mouseup', onUp);
  if (dragging.value) {
    document.body.style.cursor = '';
    document.body.style.userSelect = '';
  }
});

watch(
  () => props.initialLeftWidth,
  (w) => {
    if (!props.storageKey) leftWidth.value = w;
  }
);

const switchTab = (tab: 'left' | 'right') => {
  activeTab.value = tab;
};

defineExpose({ switchTab });
</script>

<template>
  <div
    ref="containerRef"
    class="pio-w-full pio-h-full pio-flex pio-flex-col md:pio-flex-row pio-min-h-0 pio-min-w-0"
  >
    <!-- 移动端 Tab 模式 -->
    <template v-if="mobileTabMode && !isDesktop">
      <div class="pio-flex pio-flex-shrink-0 pio-border-b pio-border-line-weak pio-bg-surface-toolbar">
        <button
          type="button"
          class="pio-flex-1 pio-py-2.5 pio-text-sm pio-transition-colors"
          :class="activeTab === 'left'
            ? 'pio-text-fg-primary pio-border-b-2 pio-border-fg-primary -pio-mb-px'
            : 'pio-text-fg-secondary'"
          @click="switchTab('left')"
        >
          {{ leftTabLabel }}
        </button>
        <button
          type="button"
          class="pio-flex-1 pio-py-2.5 pio-text-sm pio-transition-colors"
          :class="activeTab === 'right'
            ? 'pio-text-fg-primary pio-border-b-2 pio-border-fg-primary -pio-mb-px'
            : 'pio-text-fg-secondary'"
          @click="switchTab('right')"
        >
          {{ rightTabLabel }}
        </button>
      </div>
      <div v-show="activeTab === 'left'" class="pio-flex-1 pio-min-h-0 pio-min-w-0 pio-w-full pio-overflow-hidden">
        <slot name="left" />
      </div>
      <div v-show="activeTab === 'right'" class="pio-flex-1 pio-min-h-0 pio-min-w-0 pio-w-full pio-overflow-hidden">
        <slot name="right" />
      </div>
    </template>

    <!-- 桌面端 / 移动端默认堆叠模式 -->
    <template v-else>
      <div
        class="pio-min-h-0 pio-min-w-0 pio-flex-shrink-0 pio-w-full pio-max-h-60 md:pio-h-full md:pio-max-h-none"
        :style="leftStyle"
      >
        <slot name="left" />
      </div>
      <div
        role="separator"
        aria-orientation="vertical"
        class="split-divider pio-hidden md:pio-block pio-relative pio-w-1.5 pio-flex-shrink-0 pio-cursor-col-resize pio-transition-colors"
        :class="dragging ? 'dragging' : ''"
        @mousedown="onDividerDown"
      >
        <span class="pio-absolute pio-inset-y-0 hit-area" />
      </div>
      <div class="pio-flex-1 pio-min-w-0 pio-min-h-0 pio-overflow-hidden">
        <slot name="right" />
      </div>
    </template>
  </div>
</template>

<style scoped>
.split-divider {
  background: rgba(255, 255, 255, 0.1);
}
.split-divider:hover {
  background: rgba(255, 255, 255, 0.3);
}
.split-divider.dragging {
  background: rgba(255, 255, 255, 0.4);
}
.hit-area {
  left: -4px;
  right: -4px;
}
</style>
