// packages/vue/src/renderers/Pptx/index.vue
<script setup lang="ts">
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';

import { ref, watch, onMounted, onBeforeUnmount } from 'vue';
import { init } from 'pptx-preview';
import { loadOfficeFile } from '@pioneer/core';
import { useTranslator } from '../../composables/useTranslator';
import { useFetcher } from '../../composables/useRequest';
import RendererError from '../RendererError.vue';

const props = withDefaults(
  defineProps<{
    url: string;
    tiled?: boolean;
  }>(),
  { tiled: true }
);

const { t } = useTranslator();
const fetcher = useFetcher();

const loading = ref(true);
const error = ref<string | null>(null);
const slideCount = ref(0);
const containerRef = ref<HTMLDivElement | null>(null);
let previewer: ReturnType<typeof init> | null = null;
let resizeObserver: ResizeObserver | null = null;
let arrayBufferRef: ArrayBuffer | null = null;
let resizeTimeout: number | null = null;
let lastDimensions = { width: 0, height: 0 };

const calculateDimensions = () => {
  if (!containerRef.value) return { width: 960, height: 540 };
  const rawWidth = containerRef.value.clientWidth;
  const parentWidth = containerRef.value.parentElement?.clientWidth || 0;
  const containerWidth = rawWidth > 100 ? rawWidth : parentWidth > 100 ? parentWidth : 300;
  const height = Math.floor((containerWidth * 9) / 16);
  return { width: containerWidth, height };
};

const reinitializePreviewer = async () => {
  if (!containerRef.value || !arrayBufferRef || slideCount.value === 0) return;

  try {
    if (previewer) {
      try {
        previewer.destroy();
      } catch {
        // ignore
      }
    }

    containerRef.value.innerHTML = '';

    const currentDimensions = calculateDimensions();
    previewer = init(containerRef.value, {
      width: currentDimensions.width,
      height: props.tiled ? currentDimensions.height * slideCount.value : currentDimensions.height,
      mode: props.tiled ? 'list' : 'slide',
    });

    await previewer.preview(arrayBufferRef);
  } catch {
    // 静默处理
  }
};

const loadPptx = async () => {
  if (!containerRef.value) return;

  loading.value = true;
  error.value = null;

  let timeoutId: number | null = window.setTimeout(() => {
    error.value = t.value('pptx.timeout');
    loading.value = false;
  }, 30000);

  try {
    // 文件缓存优先：命中则跳过网络下载（pptx 通常较大，重复下载代价高）
    const { arrayBuffer } = await loadOfficeFile(props.url, {
      fetcher: fetcher.value,
      init: {
        mode: 'cors',
        credentials: 'omit',
        redirect: 'follow',
      },
    });
    if (arrayBuffer.byteLength === 0) throw new Error('文件为空');

    arrayBufferRef = arrayBuffer;

    // 步骤 1: 创建隐藏容器获取 slideCount
    const hiddenContainer = document.createElement('div');
    hiddenContainer.style.cssText = 'position:absolute;left:-9999px;top:-9999px;visibility:hidden';
    document.body.appendChild(hiddenContainer);

    try {
      const tempPreviewer = init(hiddenContainer, {
        width: 100,
        height: 100,
        mode: 'slide',
      });

      try {
        await tempPreviewer.preview(arrayBuffer);
      } catch {
        throw new Error(t.value('pptx.invalid_format'));
      }

      const count = tempPreviewer.slideCount;
      if (!count || count === 0) throw new Error(t.value('pptx.no_pages'));

      tempPreviewer.destroy();

      slideCount.value = count;

      if (containerRef.value) {
        containerRef.value.innerHTML = '';
      }

      const currentDimensions = calculateDimensions();
      previewer = init(containerRef.value, {
        width: currentDimensions.width,
        height: props.tiled ? currentDimensions.height * count : currentDimensions.height,
        mode: props.tiled ? 'list' : 'slide',
      });

      await previewer.preview(arrayBuffer);

      if (timeoutId !== null) {
        clearTimeout(timeoutId);
        timeoutId = null;
      }

      loading.value = false;
    } finally {
      if (document.body.contains(hiddenContainer)) {
        document.body.removeChild(hiddenContainer);
      }
    }
  } catch (err) {
    if (timeoutId !== null) clearTimeout(timeoutId);
    // 识别流式加载抛出的 HTTP 状态错误，映射为友好提示
    const statusMatch = err instanceof Error ? /请求失败: (\d+)/.exec(err.message) : null;
    let errorMsg = t.value('pptx.parse_failed');
    if (statusMatch) {
      const status = Number(statusMatch[1]);
      if (status === 404) errorMsg = t.value('pptx.not_found');
      else if (status === 403) errorMsg = '无权限访问此文件';
      else if (status >= 500) errorMsg = '服务器错误，请稍后重试';
      else errorMsg = `文件加载失败 (${status})`;
    } else if (err instanceof Error) {
      errorMsg = err.message;
    } else if (typeof err === 'string') {
      errorMsg = err;
    }
    error.value = errorMsg;
    loading.value = false;
  }
};

onMounted(() => {
  if (!containerRef.value) return;

  let isInitialRender = true;

  resizeObserver = new ResizeObserver(() => {
    if (isInitialRender) {
      isInitialRender = false;
      lastDimensions = calculateDimensions();
      return;
    }

    const newDimensions = calculateDimensions();
    const widthDiff = Math.abs(lastDimensions.width - newDimensions.width);
    const heightDiff = Math.abs(lastDimensions.height - newDimensions.height);

    if (widthDiff < 10 && heightDiff < 10) return;

    lastDimensions = newDimensions;

    if (resizeTimeout !== null) clearTimeout(resizeTimeout);

    resizeTimeout = window.setTimeout(() => {
      if (previewer && arrayBufferRef) reinitializePreviewer();
    }, 800);
  });

  resizeObserver.observe(containerRef.value);

  setTimeout(() => {
    requestAnimationFrame(() => requestAnimationFrame(() => loadPptx()));
  }, 150);
});

watch(
  () => props.url,
  (newUrl) => {
    // 只有 URL 有效时才加载（避免空字符串或已 revoke 的 blob URL）
    if (newUrl) {
      loadPptx();
    }
  }
);

onBeforeUnmount(() => {
  if (resizeObserver) resizeObserver.disconnect();
  if (resizeTimeout !== null) clearTimeout(resizeTimeout);
  arrayBufferRef = null;
  slideCount.value = 0;
  if (previewer) {
    try {
      previewer.destroy();
    } catch {
      // ignore
    }
  }
  previewer = null;
});

const getToolbarGroups = (): ToolbarGroup[] => [];

defineExpose<RendererHandle>({
  getToolbarGroups,
});

</script>

<template>
  <div class="pio-relative pio-flex pio-flex-col pio-items-center pio-w-full pio-h-full">
    <div
      v-if="loading"
      class="pio-absolute pio-inset-0 pio-flex pio-items-center pio-justify-center pio-bg-surface-toolbar pio-backdrop-blur-sm pio-z-10"
    >
      <div class="pio-text-center">
        <div
          class="pio-w-10 pio-h-10 md:pio-w-12 md:pio-h-12 pio-mx-auto pio-mb-3 pio-border-4 pio-border-line-strong pio-border-t-spinner-head pio-rounded-full pio-animate-spin"
        />
        <p class="pio-text-xs md:pio-text-sm pio-text-fg-secondary pio-font-medium">{{ t('pptx.loading') }}</p>
      </div>
    </div>

    <RendererError
      v-if="error && !loading"
      :message="t('pptx.load_failed')"
      :detail="error"
      class="pio-absolute pio-inset-0 pio-bg-surface-toolbar pio-backdrop-blur-sm pio-z-10"
    />

    <div
      v-if="!error"
      ref="containerRef"
      class="pptx-wrapper pio-w-full pio-max-w-full md:pio-max-w-6xl"
      :style="{ opacity: loading ? 0 : 1 }"
    />
  </div>
</template>

// packages/react/src/renderers/Pptx/index.tsx
import { useState, useEffect, useRef, useCallback, forwardRef, useImperativeHandle } from 'react';
import { init } from 'pptx-preview';
import { loadOfficeFile } from '@pioneer/core';
import { useTranslator } from '../../i18n/LocaleContext';
import { useFetcher } from '../../RequestContext';
import { RendererError } from '../RendererError';
import type { RendererHandle } from '../base.types';

interface PptxRendererProps {
  url: string;
  /** 是否平铺展示所有页面，默认 true */
  tiled?: boolean;
}

export const PptxRenderer = forwardRef<RendererHandle, PptxRendererProps>(({ url, tiled = true }, ref) => {
  const t = useTranslator();
  const fetcher = useFetcher();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [slideCount, setSlideCount] = useState(0);
  const containerRef = useRef<HTMLDivElement>(null);
  const previewerRef = useRef<ReturnType<typeof init> | null>(null);
  const resizeObserverRef = useRef<ResizeObserver | null>(null);
  const arrayBufferRef = useRef<ArrayBuffer | null>(null);
  const resizeTimeoutRef = useRef<number | null>(null);
  const lastDimensionsRef = useRef({ width: 0, height: 0 });

  // 计算容器尺寸，带回退逻辑
  const calculateDimensions = useCallback(() => {
    if (!containerRef.current) return { width: 960, height: 540 };
    const rawWidth = containerRef.current.clientWidth;
    const parentWidth = containerRef.current.parentElement?.clientWidth || 0;
    // 如果容器宽度太小，回退到父容器宽度或默认最小值
    const containerWidth = rawWidth > 100 ? rawWidth : (parentWidth > 100 ? parentWidth : 300);
    // 16:9 比例
    const height = Math.floor(containerWidth * 9 / 16);
    return { width: containerWidth, height };
  }, []);

  // 重新初始化预览器
  const reinitializePreviewer = useCallback(async () => {
    if (!containerRef.current || !arrayBufferRef.current || slideCount === 0) return;

    try {
      // 销毁旧的预览器
      if (previewerRef.current) {
        try {
          previewerRef.current.destroy();
        } catch {
          // 忽略销毁错误
        }
      }

      // 清空容器
      containerRef.current.innerHTML = '';

      // 获取当前容器尺寸
      const currentDimensions = calculateDimensions();

      // 初始化新的预览器，平铺模式下高度按页数计算
      const previewer = init(containerRef.current, {
        width: currentDimensions.width,
        height: tiled ? currentDimensions.height * slideCount : currentDimensions.height,
        mode: tiled ? 'list' : 'slide',
      });
      previewerRef.current = previewer;

      // 重新预览
      await previewer.preview(arrayBufferRef.current);
    } catch {
      // 重新初始化失败，静默处理
    }
  }, [calculateDimensions, tiled, slideCount]);

  // 监听容器尺寸变化
  useEffect(() => {
    if (!containerRef.current) return;

    let isInitialRender = true;

    const updateDimensions = () => {
      // 跳过初始渲染时的尺寸检查
      if (isInitialRender) {
        isInitialRender = false;
        lastDimensionsRef.current = calculateDimensions();
        return;
      }

      const newDimensions = calculateDimensions();

      // 检查尺寸是否真正变化（至少变化10px才触发）
      const lastDimensions = lastDimensionsRef.current;
      const widthDiff = Math.abs(lastDimensions.width - newDimensions.width);
      const heightDiff = Math.abs(lastDimensions.height - newDimensions.height);

      if (widthDiff < 10 && heightDiff < 10) {
        return;
      }

      // 更新最后的尺寸
      lastDimensionsRef.current = newDimensions;

      // 清除之前的定时器
      if (resizeTimeoutRef.current) {
        clearTimeout(resizeTimeoutRef.current);
      }

      // 防抖：800ms 后重新初始化预览器
      resizeTimeoutRef.current = window.setTimeout(() => {
        if (previewerRef.current && arrayBufferRef.current) {
          reinitializePreviewer();
        }
      }, 800);
    };

    // 创建 ResizeObserver
    resizeObserverRef.current = new ResizeObserver(() => {
      updateDimensions();
    });

    // 开始观察容器
    resizeObserverRef.current.observe(containerRef.current);

    return () => {
      if (resizeObserverRef.current) {
        resizeObserverRef.current.disconnect();
      }
      if (resizeTimeoutRef.current) {
        clearTimeout(resizeTimeoutRef.current);
      }
    };
  }, [calculateDimensions, reinitializePreviewer]);

  useEffect(() => {
    // 只有 URL 有效时才加载（避免空字符串或已 revoke 的 blob URL）
    if (!url) return;

    let isMounted = true;
    let timeoutId: ReturnType<typeof setTimeout> | null = null;

    const loadPptx = async () => {
      if (!containerRef.current) return;

      setLoading(true);
      setError(null);

      // 设置30秒超时
      timeoutId = setTimeout(() => {
        if (isMounted) {
          setError(t('pptx.timeout'));
          setLoading(false);
        }
      }, 30000);

      try {
        // 文件缓存优先：命中则跳过网络下载（pptx 文件通常较大，重复下载代价高）
        const { arrayBuffer } = await loadOfficeFile(url, {
          fetcher,
          init: {
            mode: 'cors',
            credentials: 'omit',
            redirect: 'follow',
          },
        });

        // 验证文件大小
        if (arrayBuffer.byteLength === 0) {
          throw new Error('文件为空');
        }

        arrayBufferRef.current = arrayBuffer;

        if (!isMounted) return;

        // 步骤 1: 创建隐藏容器，预处理获取 slideCount
        const hiddenContainer = document.createElement('div');
        hiddenContainer.style.cssText = 'position:absolute;left:-9999px;top:-9999px;visibility:hidden';
        document.body.appendChild(hiddenContainer);

        try {
          // 在隐藏容器中初始化临时预览器获取页数
          const tempPreviewer = init(hiddenContainer, {
            width: 100,
            height: 100,
            mode: 'slide',
          });

          try {
            await tempPreviewer.preview(arrayBuffer);
          } catch {
            throw new Error(t('pptx.invalid_format'));
          }

          const count = tempPreviewer.slideCount;

          if (!count || count === 0) {
            throw new Error(t('pptx.no_pages'));
          }

          // 销毁临时预览器
          tempPreviewer.destroy();

          if (!isMounted) return;

          // 保存 slideCount
          setSlideCount(count);

          // 步骤 2: 清空真实容器并初始化
          if (containerRef.current) {
            containerRef.current.innerHTML = '';
          }

          const currentDimensions = calculateDimensions();

          // 步骤 3: 初始化真实预览器，平铺模式下使用正确的总高度
          const previewer = init(containerRef.current, {
            width: currentDimensions.width,
            height: tiled ? currentDimensions.height * count : currentDimensions.height,
            mode: tiled ? 'list' : 'slide',
          });
          previewerRef.current = previewer;

          // 步骤 4: 预览 PPTX
          await previewer.preview(arrayBuffer);

          // 清除超时定时器
          if (timeoutId) {
            clearTimeout(timeoutId);
            timeoutId = null;
          }

          if (isMounted) {
            setLoading(false);
          }
        } finally {
          // 移除隐藏容器
          if (document.body.contains(hiddenContainer)) {
            document.body.removeChild(hiddenContainer);
          }
        }
      } catch (err) {
        // 清除超时定时器
        if (timeoutId) {
          clearTimeout(timeoutId);
          timeoutId = null;
        }

        if (isMounted) {
          // 识别流式加载抛出的 HTTP 状态错误，映射为友好提示
          const statusMatch = err instanceof Error ? /请求失败: (\d+)/.exec(err.message) : null;
          let errorMsg = t('pptx.parse_failed');
          if (statusMatch) {
            const status = Number(statusMatch[1]);
            if (status === 404) {
              errorMsg = t('pptx.not_found');
            } else if (status === 403) {
              errorMsg = '无权限访问此文件';
            } else if (status >= 500) {
              errorMsg = '服务器错误，请稍后重试';
            } else {
              errorMsg = `文件加载失败 (${status})`;
            }
          } else if (err instanceof Error) {
            errorMsg = err.message;
          } else if (typeof err === 'string') {
            errorMsg = err;
          }
          setError(errorMsg);
          setLoading(false);
        }
      }
    };

    // 延迟执行，使用 requestAnimationFrame 确保 DOM 已准备好
    const timer = setTimeout(() => {
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          loadPptx();
        });
      });
    }, 150);

    // 清理函数
    return () => {
      isMounted = false;
      clearTimeout(timer);
      if (timeoutId) {
        clearTimeout(timeoutId);
      }
      arrayBufferRef.current = null;
      setSlideCount(0);
      if (previewerRef.current) {
        try {
          previewerRef.current.destroy();
        } catch {
          // 忽略销毁错误
        }
      }
      previewerRef.current = null;
    };
  }, [url, calculateDimensions, tiled]);

  // 暴露接口给父组件
  useImperativeHandle(ref, () => ({
    getToolbarGroups: () => [],
  }), []);

  return (
    <div className="pio-relative pio-flex pio-flex-col pio-items-center pio-w-full pio-h-full">
      {/* 加载状态 - 绝对定位覆盖 */}
      {loading && (
        <div className="pio-absolute pio-inset-0 pio-flex pio-items-center pio-justify-center pio-bg-surface-toolbar pio-backdrop-blur-sm pio-z-10">
          <div className="pio-text-center">
            <div className="pio-w-10 pio-h-10 md:pio-w-12 md:pio-h-12 pio-mx-auto pio-mb-3 pio-border-4 pio-border-line-strong pio-border-t-spinner-head pio-rounded-full pio-animate-spin" />
            <p className="pio-text-xs md:pio-text-sm pio-text-fg-secondary pio-font-medium">{t('pptx.loading')}</p>
          </div>
        </div>
      )}

      {/* 错误状态 - 绝对定位覆盖 */}
      {error && !loading && (
        <RendererError message={t('pptx.load_failed')} detail={error} />
      )}

      {/* PPT 容器 - 仅在非错误状态下渲染 */}
      {!error && (
        <div
          ref={containerRef}
          className="pptx-wrapper pio-w-full pio-max-w-full md:pio-max-w-6xl"
          style={{ opacity: loading ? 0 : 1 }}
        />
      )}
    </div>
  );
});
